#!/usr/bin/env python3
"""Duty Board v3.85.0 — comprehensive academy materials.

The Sales Professional lessons were summaries; the proctored banks
tested specifics the reading never taught. Every lesson across all 8
modules is rewritten comprehensively — field-by-field walkthroughs,
worked naira examples, step sequences, pitfalls — and aligned so EVERY
question's answer is explicitly taught in the materials.

Also upgrades the seeder with refresh_lessons(): replaces lesson
content on ALREADY-SEEDED modules (matched by title) and clears lesson
read-progress for them — deliberate: rewritten materials should be
re-read before sitting the exam. Question banks are untouched.

Deploy: apply -> commit -> refresh the seeded site:
  bench --site xlevel.clouderp.one execute duty_board.academy_seed_sales_pro.refresh_lessons

Anchored, idempotent. Requires v3.84.0.
Run from ~/frappe-bench/apps/duty_board.
"""

import io
import json
import os
import sys

INIT = "duty_board/__init__.py"
DATA_PATH = "duty_board/academy_sales_pro_data.json"
SEED_PATH = "duty_board/academy_seed_sales_pro.py"
CHECK_ONLY = "--check" in sys.argv

L = lambda t, est, html: {"title": t, "est": est, "html": html}

NEW_LESSONS = {
"customers": [
L("The Customer master", "10", "<p>Every selling document in ZhiftERP — quotation, sales order, delivery note, invoice — hangs off a <b>Customer</b> record. Get this master right and everything downstream defaults correctly; get it wrong and you will fight every document and every report for years. Create one from <b>Selling &gt; Customer &gt; New</b>.</p><p>The fields, one by one:</p><ul><li><b>Customer Name</b> — the legal or trading name. How the system names the <i>record</i> (by this name or by a series like CUST-00042) is a Selling Settings decision covered in Selling 8.</li><li><b>Customer Type</b> — Company or Individual. Companies can carry tax IDs and multiple contacts; individuals are simpler.</li><li><b>Customer Group</b> — answers <i>what kind</i> of customer this is: Retail, Pharmacy, Distributor, Corporate. This is one of the two dimensions every sales report slices by. Groups form a tree, so \"Pharmacy\" can sit under \"Healthcare\" and reports roll up.</li><li><b>Territory</b> — answers <i>where</i>: Lagos Mainland, Lagos Island, Abuja, South-West. Also a tree, also a core reporting dimension. Set it to the geographic region your reporting structure uses — never to a salesperson's name (people move; geography doesn't) and never to the warehouse.</li><li><b>Default Price List</b> — which set of selling rates this customer gets. When a quotation is made for them, this price list lands on the document automatically and rates flow from it.</li><li><b>Default Currency</b> — the currency their documents are priced in. If a customer's quotations keep coming up in the wrong currency, the durable fix is HERE on the master — editing each quotation treats the symptom and leaves the disease.</li></ul><p><b>The rule to internalise:</b> a customer record should always be created deliberately, with name, group, territory, currency and default price list all set at creation. \"Only a name — details later\" is how master data rots: later never comes, documents inherit blanks, and the reporting dimensions you need at year-end were never captured. The master record is a contract with your future reports.</p>"),
L("Contacts & addresses", "9", "<p>A Customer record represents the <i>company</i>. The humans you talk to and the places you deliver to are separate, linked records — <b>Contacts</b> and <b>Addresses</b> — and one customer can hold many of each.</p><p><b>Contacts</b> carry a person: first name, designation, mobile number, email. When a buyer gives you their phone number, it belongs on a Contact linked to the customer — not typed into the customer name, not buried in quotation remarks, not in Selling Settings. Contacts are searchable, reusable on documents, and survive staff turnover on both sides.</p><p><b>Addresses</b> carry locations, each typed as <b>Billing</b>, <b>Shipping</b>, or both. This is how chains are modelled: a customer with 30 branches is <b>ONE customer record with 30 shipping addresses</b> — never 30 customer records (which shatters their statement, credit limit, and history into 30 pieces), and never addresses retyped per order (which guarantees typos and unfindable history). One company, one customer, many addresses.</p><p><b>Primary flags:</b> mark exactly one contact as the primary contact and one address as the primary address. Documents pull the <b>primary contact and primary address by default</b> — not the newest, not the alphabetically first, not the last used. So when a quotation shows the wrong address, the fix is almost always on the address records (wrong one flagged primary, or the right one missing) — not on the quotation.</p><p>On any selling document you can still switch to any other of the customer's addresses — the shipping address field is a picker over their address list. The primary just decides the starting point.</p>"),
L("Credit limits & the credit controller", "9", "<p>Selling on credit is lending. The <b>Credit Limit</b>, set on the customer (Credit Limits section — it can differ per company), caps how much <b>unpaid outstanding exposure</b> you will carry for them. Note precisely what it measures: not lifetime purchases, not number of orders, not a discount ceiling — the total of their <b>unpaid invoices plus committed orders</b> at this moment.</p><p><b>The enforcement:</b> when a new Sales Order (or invoice) would push the customer's outstanding past the limit, ZhiftERP <b>blocks submission</b> with a credit-limit message. The salesperson cannot proceed. This is deliberate friction: the moment of maximum temptation to over-extend is the moment the deal is closing.</p><p><b>The exception process:</b> only a user holding the <b>Credit Controller</b> role can let a blocked document through — deliberately, per document, leaving their name on the decision. Not any System Manager by default, not the salesperson who raised it, and not \"nobody until it's paid\" — the controller role exists precisely so that exceptions are possible but owned. In a well-run firm the Credit Controller is a finance person, not a sales person: the one who wants the deal should not be the one who waives the risk.</p><p><b>Why this matters commercially:</b> the difference between a sales team that grows revenue and one that grows bad debt is rarely talent — it is whether credit policy is enforced by the system at entry or \"reviewed\" by a human at month-end, after the goods have left. Set limits from payment history; review them quarterly; let the block do its job.</p>"),
L("Selling Settings that matter", "8", "<p><b>Selling Settings</b> (type it into the awesome bar) is a single screen of switches that shape every seller's day. Selling 8 gives it the full deep treatment; here are the ones you must know from day one:</p><ul><li><b>Allow Item to be Added Multiple Times in a Transaction</b> — THE switch controlling whether the same item can appear on two rows of one order. Off, a duplicate row is rejected; on, you can sell the same item at two rates on one document (100 units at standard, 20 promotional units free-of-charge, as separate rows). It lives here in Selling Settings — not on the item master, not on the price list, not in a print format.</li><li><b>Maintain Same Rate Throughout Sales Cycle</b> — enforces that the rate agreed on the Sales Order cannot silently differ on the Delivery Note or Sales Invoice made from it. What it protects against is precisely <i>rate drift between documents</i>: the ₦850 the customer agreed becoming ₦880 at invoice because someone \"corrected\" it. It does not manage currency, discounts, or taxes — those have their own machinery.</li><li><b>Customer Naming By</b> — name vs naming series, covered deeply in Selling 8.</li><li><b>Default Price List / Customer Group / Territory</b> — what new records and documents pre-fill with when nobody chooses.</li></ul><p>The habit to build: when a client asks \"can the system stop staff doing X?\", check Selling Settings first. Most selling-policy questions are answered by one of these switches, and knowing them cold is what separates a consultant from a user.</p>"),
],
"items_prices": [
L("The sellable item", "10", "<p>Nothing sells until it exists as an <b>Item</b> — and not every item sells. The gate is one checkbox: <b>Is Sales Item</b>. If an item refuses to appear on a quotation, this is the FIRST thing to check — before its price, before the customer, before the warehouse. Purchase-only components, internal consumables, and fixed assets keep it unticked and stay invisible to selling documents.</p><p>The fields that matter to a seller:</p><ul><li><b>Item Code &amp; Item Name</b> — code is the permanent identity; name is the label. Codes never change once transactions exist.</li><li><b>Item Group</b> — the reporting dimension: it serves for items exactly what <b>Customer Group</b> serves for customers (segment/rollup for analysis). Beverages, Antibiotics, Hardware — a tree, sliced by every sales report.</li><li><b>Default Unit of Measure (UOM)</b> — the unit stock is <i>counted</i> in. This is the stock-keeping unit: if the warehouse counts pieces, the default UOM is \"Unit\" (or \"Nos\"), full stop.</li><li><b>Sales UOM</b> — the unit you <i>sell</i> in, when it differs. Keep stock in Units, sell in Cartons of 12: set Sales UOM = Carton with a <b>conversion factor of 12</b> in the UOM table, and ZhiftERP does the arithmetic — a quotation for 5 Cartons deducts 60 Units. Two item records for the same product is the wrong answer; manual arithmetic on each row is the disastrous one.</li><li><b>Maintain Stock</b> — ticked for physical goods; unticked for services and (as Selling 8 teaches) bundle parents.</li></ul><p>Serial and batch tracking flags also live on the item — they matter at delivery time and are covered in Selling 5.</p>"),
L("Price lists", "9", "<p>A <b>Price List</b> is a named collection of selling rates in <b>exactly one currency</b> — that constraint is structural, not advisory. \"Standard Selling\" in NGN, \"Distributor NGN\", \"Export USD\": three lists, three commercial realities.</p><p><b>How a document finds its rates:</b> every quotation/order carries a price list field; rates for its rows are looked up from that list. The list lands on the document from the <b>customer's Default Price List</b> field — this defaulting chain (customer → document → row rates) is the machinery to understand. Selling Settings holds a global fallback for customers with none set.</p><p><b>The design principle — price lists over discounts:</b> when retail pays ₦1,000 and distributors pay ₦850 for the same item, the clean model is <b>two price lists, each with its own Item Price</b> — not a 15% discount applied to distributors, not two item records, and certainly not editing the rate by hand each time. Why it matters: with separate lists, every report shows the true agreed rate for each channel; with discounts, every analysis must mentally un-discount, margins blur, and \"discount\" stops meaning anything exceptional. Discounts (Selling 6) are for <i>exceptions</i>; price lists are for <i>structures</i>.</p><p>Buying price lists exist too (same machinery, buying side) — a consultant should never confuse which side a list serves; the \"Selling\" checkbox on the price list says which.</p>"),
L("Item Price records", "9", "<p>The price list is the folder; the actual number lives in an <b>Item Price</b> record: one item + one price list + one rate. ₦1,000 for Paracetamol-500 on Standard Selling is one Item Price row. Optional refinements on the record: <b>valid from / valid upto</b> dates (a promo rate that expires itself) and a <b>minimum quantity</b> (this rate applies from 50 units up) — those two, not warehouse, not salesperson, not payment terms, are how an Item Price is scoped.</p><p><b>The most common support ticket in selling, ever:</b> \"why is my rate 0?\" The answer, overwhelmingly: <b>no Item Price exists for that item on the document's price list</b>. The document asked its price list for a rate, the list had no row for the item, zero came back. Not the item being inactive, not taxes, not the customer's territory. Check Item Price first, always — you will close half your future support tickets with this one habit.</p><p><b>Bulk maintenance:</b> quarter-start repricing of 300 items is an <b>import job</b>: export the Item Prices via Data Export, update the rate column in the spreadsheet, re-import. Never retype fifty rates by hand (typos become invoices), never delete and rebuild the price list (history evaporates), and don't abuse pricing rules to patch what is really a base-rate change.</p>"),
L("Currency & conversion", "8", "<p>One price list, one currency — so what happens when a <b>USD price list</b> meets a document in naira? Not an error, not zero rates, and not USD showing on a naira invoice: ZhiftERP <b>converts automatically</b> using the <b>Currency Exchange</b> rate into the document's currency, and shows the conversion rate used on the document itself.</p><p>Exchange rates come from the Currency Exchange records (which can auto-fetch daily). For import-priced goods quoted locally, this means your naira quotations track the dollar without anyone editing price lists — the USD list holds the stable dollar price; conversion happens per document at the current rate.</p><p><b>The rule of thumb for structuring:</b> one price list per currency per commercial arrangement, with the <b>customer's default</b> doing the choosing. A Ghanaian distributor gets \"Distributor USD\" as their default; a Lagos pharmacy gets \"Standard Selling\" in NGN; nobody picks lists manually at quotation time, and nobody maintains a naira copy of dollar prices that goes stale the day the rate moves.</p><p>Multi-currency selling also touches the customer's receivable account currency and payment handling — the accounting depths belong to the Accounts track; a Sales Professional needs the pricing mechanics above.</p>"),
],
"quotations": [
L("Creating the offer", "10", "<p>The <b>Quotation</b> is the first formal document of the cycle — the written offer. It can be made against an existing <b>Customer</b> or against a <b>Lead</b> (someone not yet a customer) — that flexibility matters: you don't create a customer master just to price an enquiry. Create from <b>Selling &gt; Quotation &gt; New</b>, or from a CRM opportunity so the trail from first contact to offer stays linked.</p><p>What you fill:</p><ul><li><b>Party</b> — the customer or lead. Their price list, currency, contact and address default in.</li><li><b>Items</b> — code, quantity; the <b>rate arrives from the price list</b> automatically per the previous module.</li><li><b>Rate overrides</b> — you MAY type over a price-list rate on any row. This is allowed, visible, and reportable — not forbidden, not manager-only, not automatic. The philosophy: empower the negotiation, but leave fingerprints. Reports can always compare charged rate vs list rate.</li><li><b>Valid Till</b> — how long the offer stands. After this date the quotation automatically shows <b>Expired</b>. Fill it always: open-ended offers are how last year's prices get accepted this year.</li><li><b>Payment terms, terms &amp; conditions</b> — the commercial fine print that will travel forward.</li></ul><p>Save produces a Draft you can still edit; <b>Submit</b> makes it a formal, numbered offer and moves it to Open. Print formats give it your letterhead for the customer's inbox.</p>"),
L("Taxes on the quotation", "8", "<p>Quote taxes ON the offer — this is both mechanics and commercial judgment.</p><p><b>Mechanics:</b> attach a <b>Sales Taxes and Charges Template</b> to the quotation — for Nigerian trade typically <b>VAT at 7.5%</b> — and the document computes and displays the tax rows and the grand total. VAT is never typed into item rates by hand and never derived from the customer group; the template row (account head + 7.5%) does it uniformly. Building the templates is covered deeply in Selling 6; here you need to know that one is <i>selected on the document</i> and does the work.</p><p><b>Commercial judgment:</b> the reason to quote taxes is that <b>the customer sees the true payable total from the first document</b>. Quote ₦10m clean, invoice ₦10.75m later, and you have manufactured a dispute at the worst possible moment — after commitment, before payment. It is not a legal requirement on quotations that drives this; it is deal hygiene. No late surprises.</p><p><b>The template travels:</b> the taxes chosen on the quotation <b>flow onto the Sales Order</b> made from it, and onward to delivery and invoice. Nobody re-enters taxes at each stage, and the offer's arithmetic is the invoice's arithmetic.</p>"),
L("The status lifecycle", "8", "<p>A quotation's status is one word telling you exactly where the deal stands. Learn the vocabulary cold:</p><ul><li><b>Draft</b> — being written; editable; not yet an offer.</li><li><b>Open</b> — submitted and awaiting the customer's answer. THE working state.</li><li><b>Ordered</b> — won: a Sales Order has been made from it.</li><li><b>Lost</b> — conceded, with a reason recorded.</li><li><b>Expired</b> — Valid Till passed with no order; automatic.</li><li><b>Cancelled</b> — withdrawn by you.</li></ul><p><b>The operational habit:</b> the Quotation list filtered to <b>Open</b> IS your offers-awaiting-answer pipeline — not Draft (those aren't offers yet), not All (that's history). A sales professional works that filter weekly: chase the old ones, expire-and-refresh the stale ones, mark the dead ones Lost honestly. An Open list you can trust is worth more than any forecast, because it's not a forecast — it's the actual set of live offers.</p>"),
L("Losing well & converting", "8", "<p><b>Losing well:</b> when a deal dies, mark the quotation <b>Lost</b> — and ZhiftERP prompts for a <b>Lost Reason</b>: price, competitor, timing, no budget, spec mismatch. Recording it costs ten seconds. Six months of honest lost reasons is a strategy document nobody had to write: if \"price\" dominates in one segment, your list rates are wrong there; if one competitor's name keeps appearing, you know exactly who to build battle-cards against. Lost reasons are <b>competitive and pricing intelligence</b> — not a blame record for reps, not noise, not a deletion queue. Teams that fake them (everything is \"timing\") throw the intelligence away.</p><p><b>Winning:</b> when the customer says yes, do NOT open a blank Sales Order and retype. From the quotation: <b>Create &gt; Sales Order</b>. Everything carries across — items, quantities, rates (including your negotiated overrides), taxes, terms — with <b>no transcription errors</b>, and the quotation flips to <b>Ordered</b>, closing the loop. The point of document flow is that the offer the customer accepted is BYTE-FOR-BYTE the order you fulfil; the moment someone retypes, the agreed deal and the recorded deal can diverge, and every dispute that follows is your fault.</p><p>This create-from-the-previous-document pattern is the spine of the whole cycle: quotation → order → delivery note → invoice, each born from its parent, nothing retyped, the chain of custody unbroken.</p>"),
],
"sales_orders": [
L("The commitment", "8", "<p>The <b>Sales Order</b> is where an offer becomes an obligation. The customer has said yes; you now owe specific goods at specific rates by a specific <b>Delivery Date</b> — and the business plans around that promise: stock gets reserved, procurement sees demand, the warehouse sees a pipeline of picks.</p><p><b>Preferred origin:</b> created FROM the accepted quotation (Create &gt; Sales Order), inheriting everything — the previous module explained why retyping is malpractice. Direct entry exists for genuinely quotation-less sales (repeat standing orders, counter trade), but \"direct entry always\" is the mark of a team not using the system's spine.</p><p><b>Delivery dates, properly:</b> the order carries a header delivery date, and each row can carry its OWN — because real orders split: the shelving ships Monday, the imported scanners in three weeks. <b>Per-row delivery dates on one order</b> is the correct model for staggered fulfilment — not separate orders per timeline (which fragments the customer's one purchase), not remarks (which no report reads), not holding the whole order hostage to its slowest line.</p><p>The order also fixes the commercial terms for the rest of the cycle: rates, taxes, payment terms — which the Maintain-Same-Rate setting then defends downstream.</p>"),
L("What submission does", "8", "<p>Submitting a Sales Order is not filing paperwork — it changes system state in two ways every seller must understand:</p><p><b>1. Stock intent is committed.</b> The ordered quantities appear as <b>reserved</b> against the warehouse. Reserved stock is not deducted (deduction is the Delivery Note's job, next module), and nothing transfers to the customer yet — but everyone SEES the promise: another salesperson checking availability sees actual-minus-reserved; the planner sees demand; procurement sees what must be bought. Reservation is the mechanism that stops two reps selling the same last 50 cartons.</p><p><b>2. The fulfilment ledger opens.</b> The order now tracks, per row: quantity ordered, <b>delivered so far</b>, <b>billed so far</b>. Every Delivery Note and Sales Invoice <b>made FROM the order</b> counts these down automatically. That's why creating downstream documents from the order matters mechanically, not just for convenience: a delivery note typed from scratch doesn't count against anything, and the order will insist those goods are still owed. The remaining quantities count down as <b>Delivery Notes are made from the order</b> — not as payments arrive, not as time passes, not as stock is purchased.</p>"),
L("Status language & control", "10", "<p>Order status is a compact sentence about what remains owed. The vocabulary:</p><ul><li><b>To Deliver and Bill</b> — freshly submitted; both obligations outstanding. Every order starts here.</li><li><b>To Bill</b> — delivered in full, not yet invoiced. Goods gone; money not asked for.</li><li><b>To Deliver</b> — invoiced first (advance-billing deals), goods still owed.</li><li><b>Completed</b> — both done.</li></ul><p>Two manual controls change an order's course:</p><ul><li><b>Hold</b> — pauses the order. Credit trouble, stock uncertainty, customer says \"wait\": Hold keeps the commitment intact but stops fulfilment. Not cancellation, not closure — a pause.</li><li><b>Close</b> — ends it early, deliberately. The classic case: customer took 80 of 100 and will take no more. Closing the order <b>releases the reserved stock</b> for the remaining 20 and removes the order from every pending-delivery list — the honest end. Cancelling would falsify history (the 80 DID happen); deleting rows mutilates a submitted document; delivering 20 to scrap is absurd. <b>Close is the answer</b> — know this cold.</li></ul><p><b>Amending:</b> submitted documents don't get edited — they get <b>cancelled and Amended</b>, which creates the next revision (same number, -1 suffix) with the original preserved in history. Quantities changed, rows added: cancel → Amend → adjust → resubmit. Never a fresh order pretending the first didn't exist, and never database surgery.</p>"),
L("Delivery tolerance", "7", "<p>Paper says 100; the pallet holds 102. Real warehouses overship slightly — bulk goods, pack rounding, good-faith extras — and the system must decide whether to allow it.</p><p>The <b>Over Delivery/Receipt Allowance %</b> answers it: set on the <b>item</b> (per-product tolerance) or globally in settings (the fallback), it defines how much a delivery may exceed the ordered quantity before ZhiftERP <b>blocks the delivery note</b>. Allowance 5% on an order of 100 → deliveries up to 105 pass; 106 is refused. Shipping 102 against 100 is permitted <b>when the allowance covers the 2%</b> — not never, not because the driver insists, and the invoice has nothing to do with it.</p><p><b>Choosing the number is a policy decision, per item class:</b> <b>zero tolerance</b> is right for <b>serialized electronics</b> — every unit has an identity, 100 means exactly 100 serials; slack there is how phones vanish. Bulk cement, produce, consumables earn a few percent, because blocking a 101st bag helps nobody. \"Zero for everything\" strangles the warehouse; \"slack for everything\" leaks serialized stock. Match tolerance to the nature of the goods.</p>"),
],
"delivery": [
L("The document that moves stock", "8", "<p>Everything before this module was promise; the <b>Delivery Note</b> is physics. <b>Submitting a Delivery Note deducts stock from the warehouse.</b> Fix the timeline in your head permanently: quotation moves nothing, Sales Order <i>reserves</i>, <b>Delivery Note deducts</b>, invoice moves money, payment settles it. When a client asks \"why does my stock report still show those goods?\", the first question is \"has the delivery note been submitted?\"</p><p><b>Creation discipline:</b> from the Sales Order — <b>Create &gt; Delivery Note</b> — never from scratch, never by copying an old DN. Three reasons: quantities, rates and taxes flow correctly; the order's fulfilment ledger counts down (a from-scratch DN counts against nothing, and the order will insist the goods are still owed); and the document chain stays auditable — this DN fulfils that order fulfils that quotation.</p><p>The DN records the warehouse each row ships from, the shipping address chosen from the customer's addresses, and the transporter details when you need them on the waybill. Its print format IS the delivery document your driver carries and the customer's gate signs.</p>"),
L("Partial delivery & status", "8", "<p>Orders rarely ship whole. The mechanics of shipping 60 of 100 today:</p><p>Create the DN from the order and <b>edit the quantity down to 60</b> on the row. Submit. The order's ledger now shows 60 delivered, 40 remaining — and here is the part that makes the system trustworthy: <b>the next DN created from that order offers exactly the 40 remaining</b>. Not 100 again (no double-shipping), not whatever someone types from memory. The order arithmetic is authoritative.</p><p><b>Where to see undelivered backlog:</b> remaining-to-deliver is <b>order-side data</b> — read it on the Sales Order itself or across all orders in the order-analysis reports (Selling 6 names them). The DN list can't tell you what HASN'T shipped; only orders know what they're still owed.</p><p><b>DN status:</b> a submitted DN reads <b>To Bill</b> until a Sales Invoice covers it, then <b>Completed</b>. \"To Bill\" on a DN is a small alarm: goods have left the building and nobody has asked for money yet — a list of To-Bill DNs older than a few days is revenue leaking.</p><p><b>Direction of creation can also reverse:</b> in advance-billing flows where the Sales Invoice came first, the DN is created <b>against the invoice</b> — same chain, opposite order. A DN is never made against a quotation, a lead, or a price list.</p>"),
L("Sales returns", "9", "<p>Goods come back — wrong spec, damaged in transit, customer over-ordered. The clean reversal has two halves, and this module owns the stock half.</p><p><b>The Sales Return is a Delivery Note with <i>Is Return</i> ticked</b>, created <b>against the original DN</b>, carrying <b>negative quantities</b>. Submitting it moves stock <b>back INTO the warehouse</b> — the exact mirror of the outbound. Three properties make this the only correct method:</p><ul><li><b>Traceability</b> — the return references the precise original shipment: which DN, which batch, which serials came back. An unlinked \"stock adjustment\" restores quantity but destroys the story; deleting the original DN falsifies history; a purchase receipt is a different doctype for a different trading partner entirely.</li><li><b>Valuation</b> — the return re-enters stock at the correct value, because it knows what left.</li><li><b>Partiality</b> — return 5 of the 60 shipped; the negative rows say exactly which 5.</li></ul><p><b>The money half is a separate document:</b> the customer's refund or credit is the <b>credit note</b> — a return Sales Invoice — covered in Selling 7. Stock reverses on the return DN; money reverses on the credit note; the two link to their respective originals. One event, two ledgers, two documents. The return DN itself does not touch the customer's balance, and cash from the driver is not an accounting system.</p>"),
L("Packing slips, serials & batches", "8", "<p>Three companions to the DN that turn \"we shipped it\" into an operation:</p><p><b>Packing Slip</b> — created against the DN, it lists <b>cartons and their contents</b>: case 1 of 3 holds these items, case 2 holds those. Its audience is the <b>driver and the receiving gate</b> — the people who count boxes, not lines. It does not replace the DN (no stock effect), charges nothing, and reserves nothing; it is the physical-handling companion. Multi-carton B2B shipments without packing slips produce gate disputes; with them, the gate ticks cartons and signs.</p><p><b>Serial numbers</b> — an item flagged serialized requires <b>the exact serial numbers being shipped</b> entered on the DN row. Not \"any 10 units\": THESE ten, by identity. That per-unit identity is what powers warranty claims (\"was this unit ours, and when did it ship?\") and theft control. It requires no manager approval and no batch number — it requires the serials.</p><p><b>Batches</b> — batch-tracked items (pharma, food) record <b>which batch</b> each DN row shipped. The payoff is the recall question: <i>\"which customers received batch B-204?\"</i> — answerable in seconds by searching DNs for the batch, because <b>batch numbers are recorded on each Delivery Note</b>. Not because drivers keep notebooks, and not from invoices (money documents, not movement documents). For your pharmacy clients this is regulatory survival: NAFDAC recall queries are DN queries.</p>"),
],
"taxes_invoicing": [
L("Sales taxes & VAT", "10", "<p>Tax setup is write-once, apply-everywhere. The <b>Sales Taxes and Charges Template</b> defines the tax rows a selling document carries — for Nigerian trade, a template with one row: <b>VAT, 7.5%, On Net Total</b>, posting to your VAT output liability account. Selecting that template on any quotation, order, or invoice applies VAT uniformly — never typed per row, never inferred from the customer master, never a pricing rule's job. Build once; select everywhere; when FIRS changes the rate, change one template.</p><p><b>Item-level overrides:</b> not everything is standard-rated. A <b>zero-rated or exempt item</b> sitting on an otherwise VAT-able invoice is handled by an <b>Item Tax Template</b> attached to that item, overriding the document rate <b>for that row only</b> — 7.5% on the taxable rows, 0% on the exempt one, one invoice, correct return. You do not delete the document's tax row (breaking the other rows), split invoices, or fake it with a discount.</p><p><b>Inclusive vs exclusive — get the arithmetic reflexive:</b> <b>exclusive</b> (the default) adds tax on top: rate ₦1,000 → total ₦1,075. <b>Inclusive</b> (a checkbox on the tax row) means the entered rate already CONTAINS the tax: ₦1,075 inclusive at 7.5% = <b>₦1,000 net + ₦75 VAT</b> (divide by 1.075). Retail prices are typically quoted inclusive; B2B exclusive. Mixing them up misstates either your price (charging tax on tax) or your VAT return (remitting less than collected) — both expensive.</p>"),
L("Pricing rules & discounts", "9", "<p>Two instruments cut prices; a professional keeps them in the right hands.</p><p><b>Pricing Rules — policy, automated.</b> A Pricing Rule applies a discount (percentage or amount) or a special rate automatically when its conditions match. Conditions span: <b>what</b> (item, item group, brand), <b>who</b> (customer, customer group, territory), <b>how much</b> (quantity brackets — 50+ cartons), and <b>when</b> (valid from/to). So \"10% off cartons of 50+ for Distributors in Q4\" is built ONCE as a rule and fires itself on every qualifying order — not circulated as a memo (memos get forgotten and misapplied), not manually edited per order (inconsistent, invisible), not a per-quarter clone of the price list. Rules can stack with priorities when several match; keep rules few and legible.</p><p><b>Manual discounts — exceptions, visible.</b> Per document there is an <b>Additional Discount</b> (on the grand or net total) and per-row rate cuts. These exist for the genuinely exceptional negotiation. The discipline: <b>policy lives in price lists and pricing rules; manual discounts stay rare and visible</b> — reportable exceptions, not the everyday pricing method, not hidden inside doctored rates, and not banned outright (real negotiations exist). When \"exceptional\" discounts appear on every order, pricing has left the system and moved into WhatsApp — the moment to rebuild the rules.</p>"),
L("The Sales Invoice & getting paid", "9", "<p>The <b>Sales Invoice</b> is the accounting event of the cycle: submitting it <b>books revenue and the customer's receivable</b> into the ledgers. Not the order (a promise), not the DN (goods movement), not the payment (settlement of what the invoice created) — the INVOICE is where money becomes real on the books. Selling 7 dedicates a full module to its depths; here is the working core.</p><p><b>Creation:</b> from the Sales Order (billing ahead of or with delivery) or from the Delivery Note (billing exactly what shipped) — the same no-retyping spine. Quantities, rates, taxes flow; the order's billed-quantity ledger counts down.</p><p><b>Getting paid:</b> money arrives as a <b>Payment Entry</b> — full payment closes the invoice; a partial leaves it Partly Paid with the outstanding visible; and <b>one customer payment covering several invoices is ONE Payment Entry allocated across all of them</b> — not three separate entries, not a bare journal, and certainly not a credit note (that reverses revenue, the opposite of receiving it!).</p><p><b>Status = the collections story:</b> <b>Unpaid</b> → <b>Partly Paid</b> → <b>Paid</b>; and the moment the due date passes unpaid, <b>Overdue</b>. The invoice list filtered to Overdue is your collections worklist. Not \"Late\", not \"Blocked\" — Overdue.</p>"),
L("Credit notes & the watching reports", "9", "<p><b>The credit note:</b> when goods return or an invoice must be corrected, revenue reverses via a <b>Sales Invoice with <i>Is Return</i> ticked, made against the original invoice</b> — negative amounts pulling revenue and receivable back, linked to what they reverse. Not a special letter, not cancelling the invoice (history falsified), not a \"negative payment\". It mirrors the return DN: <b>stock reverses on the return Delivery Note; money reverses on the credit note</b> — one physical event, two ledgers, two linked documents. This pairing is what auditors — and FIRS — expect to find.</p><p><b>The three watching reports — read them weekly, not at quarter-end panic:</b></p><ul><li><b>Sales Analytics</b> — revenue sliced by customer, item, item group, territory over time. Growth, mix, and the customer quietly shrinking.</li><li><b>Sales Order Analysis</b> — ordered vs delivered vs billed across all open orders: the <b>delivery backlog</b> in one screen. This, not the DN list, answers \"what have we promised and not shipped?\"</li><li><b>Accounts Receivable</b> — <b>who owes what, aged</b> into buckets (0-30, 31-60, 61-90, 90+ days). The ageing is the point: ₦5m owed 15 days is business; ₦5m owed 95 days is a problem with a name. This is the receivables instrument — not Sales Analytics, not the stock ledger.</li></ul><p>A sales professional who reads these three weekly manages a book; one who doesn't, gets managed by it.</p>"),
],
"sales_invoice": [
L("The invoice as the accounting event", "10", "<p>Everything before it was commitment and movement; the <b>Sales Invoice</b> is where money becomes real on the books. <b>Submitting it books revenue and the customer's receivable</b> in the general ledger, dated by the invoice's <b>posting date</b>. Nothing else in the cycle does this: the order promises, the DN moves goods, the payment (later) settles what the invoice created. If the question is \"when do the books recognise this sale?\", the answer is always: at invoice submission.</p><p><b>Creation paths, chosen by flow:</b></p><ul><li><b>From the Sales Order</b> — billing ahead of or alongside delivery (advance-billing deals, services).</li><li><b>From the Delivery Note</b> — <b>billing exactly what shipped</b>: quantities on the invoice are the quantities that actually left. For partial-delivery trade this is the honest path — you invoice the 60 that went, not the 100 ordered.</li><li>Standalone — for genuinely document-less sales; rare in disciplined B2B.</li></ul><p><b>Two dates, two meanings — never conflate them:</b> the <b>posting date</b> is when the books record the sale; the <b>due date</b> is when the customer must pay. The due date is not \"posting + 30 always\" and not the delivery date: it is <b>computed from the Payment Terms</b> — Net 30, 50% advance / balance on delivery, end-of-following-month — which the invoice <b>inherits from the customer or the order</b>. Terms belong on the master or the order precisely so nobody improvises them at billing time; the seller's job is to make sure they're set BEFORE the first invoice, not negotiated after it.</p>"),
L("Statuses & the collections story", "9", "<p>An invoice's status is the collections narrative in one word:</p><ul><li><b>Unpaid</b> — submitted, no money yet.</li><li><b>Partly Paid</b> — some money allocated, outstanding remains. A ₦2m receipt against a ₦5m invoice leaves it here — visibly ₦3m short, not \"Paid\", not still \"Unpaid\".</li><li><b>Paid</b> — outstanding cleared.</li><li><b>Overdue</b> — the due date passed while unpaid (or partly paid). Automatic, merciless, useful.</li><li><b>Credit Note Issued</b> — a return invoice has been raised against it (lesson 4).</li></ul><p><b>The worklist habit:</b> the invoice list filtered to <b>Overdue, sorted oldest-first, IS collections</b>. Open it weekly. Every entry gets an action — a call, a statement, a dated next step on the Duty Board pipeline — because an overdue invoice nobody is chasing is a donation.</p><p><b>The Update Stock special case — know it to avoid double-movement:</b> an invoice with <b>Update Stock</b> ticked <b>moves inventory itself</b> — it plays both money document and delivery note. Its legitimate home is flows that skip the DN: counter sales, service jobs with materials. The trap: tick Update Stock on an invoice made FROM a Delivery Note and <b>stock moves twice</b> — once at the DN, once at the invoice — and your stock report is now lying. Standard flow: DN moves stock, invoice moves money, Update Stock stays off.</p>"),
L("Payment Entry mechanics", "10", "<p>Money arrives in every shape; the <b>Payment Entry</b> records them all. Make it FROM the invoice (Create &gt; Payment) so the reference and amounts pre-fill. The shapes:</p><ul><li><b>Full payment</b> — allocates the whole outstanding; invoice → Paid.</li><li><b>Partial payment</b> — allocate what came; invoice → Partly Paid, outstanding visible. Repeat until cleared.</li><li><b>One payment, many invoices</b> — a customer's single ₦12m transfer settling four invoices is <b>ONE Payment Entry with four allocation rows</b>, splitting the amount across the references. Never four fabricated entries for one bank line — reconciliation must match the bank statement line-for-line.</li><li><b>Advance payment</b> — money BEFORE any invoice exists (your enterprise 50%-upfront deals): a Payment Entry taken <b>against the customer</b>, sitting as an advance on their account; when the invoice is later raised, the advance is <b>allocated</b> to it. Not \"wait for the invoice to bank the cheque\", not a negative invoice, not a discount.</li><li><b>Write-off</b> — the customer pays ₦1,999,820 against ₦2m. Chasing ₦180 forever costs more than ₦180: within your configured write-off limit, the Payment Entry <b>writes off the difference</b> and closes the invoice honestly. Never edit the invoice total to match the shortfall.</li></ul><p>On every entry: <b>Mode of Payment</b> (transfer, POS, cash, cheque) and the receiving <b>bank account</b> — filled correctly at entry, these make month-end bank reconciliation a matching exercise instead of archaeology.</p>"),
L("Credit notes & receivables discipline", "9", "<p><b>Correcting a submitted invoice:</b> a submitted invoice with a wrong rate is never edited and never deleted — the audit trail is the point of submission. The correct fix is a <b>credit note against it, then re-invoice correctly</b>: the credit note is a <b>Sales Invoice with <i>Is Return</i> ticked, made against the original</b>, reversing revenue and receivable with negative amounts; the original's status flips to <b>Credit Note Issued</b> — permanently tying reversal to reversed. Then a fresh, correct invoice goes out. Auditors and FIRS expect exactly this pattern: every figure that ever hit the ledger, plus the visible document that unwound it. \"Journal patches\" to fix invoice errors are how audits go from routine to forensic.</p><p><b>For returned goods</b> the credit note is the money half of the pair from Selling 5: stock came back on the return DN; the customer's balance comes back on the credit note.</p><p><b>Receivables discipline — the weekly trinity:</b></p><ul><li><b>Accounts Receivable report</b> — who owes what, <b>aged into buckets</b> (0-30, 31-60, 61-90, 90+). Age is risk: read the right-hand columns first.</li><li><b>Statement of Account</b> — sent to each credit customer monthly. Customers dispute what they see once a quarter; they pay what they see every month.</li><li><b>A dated next step for every overdue invoice</b> — in this house that means the Duty Board pipeline's next-step discipline, applied to collections: no overdue invoice without a named person and a date on its follow-up. Hope is not a collections strategy.</li></ul><p>Selling ends when the money is in the bank. This module is the difference between revenue and cash.</p>"),
],
"advanced": [
L("Selling Settings — the full tour", "12", "<p>Selling Settings is where selling <i>policy</i> becomes system <i>behaviour</i>. A consultant should be able to defend every switch on this screen to a client's managing director. The tour:</p><p><b>Naming:</b> <b>Customer Naming By</b> — <i>Customer Name</i> makes the record's ID the name itself (\"Alpha Pharmacy\"); <i>Naming Series</i> issues CUST-00042 style IDs. The decision rule: <b>chains and portfolios with duplicate or near-duplicate names need the series</b> — a retailer with \"Adepoju Stores\" in three cities cannot key records by name without collisions. Series naming keeps identity unambiguous forever; the display name remains human.</p><p><b>Defaults:</b> Default <b>Customer Group</b>, <b>Territory</b>, and <b>Selling Price List</b> pre-fill new records and documents. Set them to your commonest case so hurried data entry lands correctly instead of blank.</p><p><b>The discipline switches — each answers a client policy question:</b></p><ul><li><i>\"Can we stop staff typing special prices?\"</i> → <b>untick Allow User to Edit Price List Rate</b>. Rates then come ONLY from Item Price records; the rate field is read-only on documents. The single strongest anti-discount control that exists — stronger than memos, smaller price lists, or threats.</li><li><i>\"Can we prevent selling below cost?\"</i> → <b>Validate Selling Price Against Purchase Rate</b>: blocks a selling rate below the item's purchase cost at the point of entry. Margin protection built into the keyboard, not discovered in a month-end report.</li><li><i>\"Can the agreed rate change between order and invoice?\"</i> → <b>Maintain Same Rate Throughout Sales Cycle</b>, whose companion <b>action setting</b> chooses the response to a drift: <b>Stop</b> (hard block) or <b>Warning</b> (allow but flag). Strict shops choose Stop; shops with legitimate mid-cycle repricing choose Warning. Not silence, not auto-correction, not an email.</li><li><b>Allow Item to be Added Multiple Times</b> — same item on two rows (standard + promo rate), from Selling 1.</li><li>The global <b>over-delivery allowance</b> — the fallback that Selling 4's per-item tolerance overrides.</li></ul><p>When a policy question arrives, check this screen before writing a customisation — nine times in ten, the switch already exists.</p>"),
L("Product Bundles", "10", "<p>You price as ONE thing but pick as MANY things: a \"Pharmacy Starter Pack\" at ₦450,000 that is really shelving units + a barcode scanner + a receipt printer. The <b>Product Bundle</b> is the correct model — never a workaround stock item whose contents live in someone's head and whose warehouse quantity nobody can honestly count.</p><p><b>The construction:</b></p><ul><li><b>The parent item</b> — created as a normal item BUT <b>non-stock: Maintain Stock UNTICKED</b>. The parent never has warehouse quantity; it is a commercial identity, not a physical one. (Not \"a stock item with quantity\", not necessarily serialized, not a service.)</li><li><b>The bundle definition</b> — the Product Bundle record lists the parent and its <b>child items with quantities</b>: 4 × shelf unit, 1 × scanner, 1 × printer.</li><li><b>Pricing</b> — an Item Price for the PARENT on your selling list: ₦450,000. Children need no selling price for the bundle to work.</li></ul><p><b>The mechanics at each document:</b> on the quotation and the <b>invoice, the customer sees ONE line at the parent's price</b> — clean commercial presentation, no per-child price exposure. On the <b>Delivery Note, the bundle EXPLODES into its packed items</b> — the children appear as the packed-items list, and <b>it is the CHILDREN that move stock</b> from the warehouse: 4 shelves, 1 scanner, 1 printer deducted; the parent deducts nothing (it has nothing to deduct). Price lives on the parent; picking lives on the children. Hampers, promo packs, starter kits, installation kits — the pattern is everywhere in Nigerian retail; model it once, correctly.</p>"),
L("Blanket Orders", "10", "<p>A customer says: \"we'll take 10,000 cartons over the next six months — what's your best rate?\" You agree ₦820. This is more than a quotation (they've committed, not enquired) and less than a Sales Order (they don't want 10,000 cartons delivered Tuesday). It is a <b>Blanket Order</b>: a long-term <b>rate-and-quantity agreement</b> consumed over time.</p><p><b>Creating it:</b> the Blanket Order carries the customer, the items with <b>agreed quantities and agreed rates</b>, and the <b>from/to dates</b> of the agreement. Submitting it creates no reservation and moves no stock — it establishes the commercial frame.</p><p><b>Drawing against it:</b> each real purchase becomes an ordinary <b>Sales Order referencing the blanket order</b> — and two things happen automatically: the order row <b>inherits the agreed ₦820 rate</b> (nobody negotiates twice, nobody \"forgets\" the deal rate), and the blanket order records the <b>drawdown</b> — ordered-so-far against committed. Not just the quantity copies, and the delivery date is per-order business, not the blanket's.</p><p><b>Reading the commitment:</b> \"how much of the 10,000 remains?\" is read <b>from the blanket order itself</b> — its ordered-vs-committed quantities — not from the customer's memory, the last invoice, or stock levels. Both sides see the same consumption truth, which is precisely what makes volume agreements governable.</p><p><b>Blanket vs the alternatives:</b> one giant 10,000-carton Sales Order reserves half a warehouse for months and lies about delivery intent. A quotation stretched to six-month validity is an <i>offer awaiting an answer</i> pretending to be an <i>agreement being consumed</i> — wrong document, wrong semantics. A pricing rule gives the rate but tracks no commitment. The blanket order is the instrument built for exactly this shape of deal — your Montaigne-class volume agreements belong here.</p>"),
L("Sales Person — the internal team", "10", "<p><b>Sales Person</b> models YOUR OWN sales force — and models it as a <b>tree</b>, not a flat list: Sales Director → Regional Managers → Field Reps. The tree is the point: results <b>roll up the hierarchy</b>, so the Lagos region's number is the sum of its reps' numbers and the director's number is the company, without anyone building spreadsheets.</p><p><b>Assignment on transactions:</b> selling documents carry a <b>Sales Team</b> section where one or MORE sales persons are attached, each with a <b>contribution %</b> — and the percentages <b>sum to 100</b>. A deal worked by two reps splits 60/40: reports then credit each with their contributed share of the revenue, <b>never double-counting</b> the deal. Not two invoices for one sale, not a note in remarks, not two \"sales partners\" (wrong concept entirely — next lesson).</p><p><b>Targets:</b> each sales person can carry targets by item group and period (monthly, quarterly). Actuals accrue from their assigned transactions.</p><p><b>The report:</b> <b>Sales Person-wise Transaction Summary</b> — each person's transactions, contributed amounts, and performance against target. League tables, commission calculations, and performance conversations all read from here.</p><p><b>The consultant's honest answer</b> — when a client asks \"can we see sales by rep?\": <i>only if sales persons are assigned on the transactions.</i> The report is arithmetic over assignments; installing it changes nothing, targets alone measure nothing, partners are a different object. <b>The discipline of assignment precedes the report</b> — configure the tree, make the Sales Team section mandatory in the client's process, and THEN the question answers itself weekly.</p>"),
L("Sales Partner — the external channel", "10", "<p>A <b>Sales Partner</b> is a business OUTSIDE your company that brings you deals — a reseller, a referral agent, a channel distributor, an implementation partner who sources clients. The record carries the partner's identity, type, and — the operative field — a <b>commission rate</b>.</p><p><b>On transactions:</b> select the Sales Partner on a Sales Order or Sales Invoice and two things happen: the deal is <b>stamped as that channel's business</b> (channel revenue becomes reportable), and the document computes the <b>total commission</b> at the partner's rate — the liability you owe them for the introduction, calculated per deal, automatically.</p><p><b>The distinction to keep razor-sharp — Person vs Partner:</b></p><ul><li><b>Sales Person</b> = <b>internal staff</b>: a tree, contribution percentages summing to 100, targets, performance management.</li><li><b>Sales Partner</b> = an <b>external business</b>: a flat entity, a commission %, a payable relationship.</li></ul><p>They are not the same thing with different names, commission is not what separates them (both can drive earnings), and a partner is not a customer. And a single transaction can legitimately carry <b>BOTH</b>: your rep (Sales Person, 100% contribution) worked a deal that a referral firm (Sales Partner, 5% commission) introduced.</p><p><b>Paying partners:</b> commissions are settled from the <b>Sales Partner-wise Transaction Summary</b> — the system's own totals of each channel's business and accrued commission. <b>Pay partners from the report, not from their claims</b>: when the partner's invoice says ₦2.4m and your summary says ₦2.1m, the summary — built from the actual stamped transactions — is the negotiating position. Channel programs die of over-payment and under-tracking; this report prevents both.</p>"),
],
}

REFRESH_SRC = '''

def refresh_lessons():
	"""Replace lesson content on ALREADY-SEEDED modules from the data
	file (matched by title). Clears lesson read-progress for refreshed
	modules — rewritten materials should be re-read. Questions untouched."""
	data = _data()
	refreshed = 0
	for key in ORDER:
		m = data[key]
		mod = frappe.db.get_value("Duty Training Module", {"title": m["title"]}, "name")
		if not mod:
			print(f"module not seeded yet (skipped): {m['title']}")
			continue
		for row in frappe.get_all("Duty Lesson", filters={"module": mod}, pluck="name"):
			frappe.delete_doc("Duty Lesson", row, ignore_permissions=True, force=True)
		for row in frappe.get_all("Duty Lesson Progress", filters={"module": mod}, pluck="name"):
			frappe.delete_doc("Duty Lesson Progress", row, ignore_permissions=True, force=True)
		for j, l in enumerate(m["lessons"]):
			frappe.get_doc(
				{
					"doctype": "Duty Lesson",
					"module": mod,
					"title": l["title"],
					"sort_order": j,
					"est_minutes": l["est"],
					"content": l["html"],
				}
			).insert(ignore_permissions=True)
		refreshed += 1
		print(f"refreshed: {m['title']} ({len(m['lessons'])} lessons)")
	frappe.db.commit()
	print(f"{refreshed} module(s) refreshed. Read-progress reset for refreshed modules.")
'''


def main():
    root = os.getcwd()
    with io.open(os.path.join(root, INIT), encoding="utf-8") as f:
        init = f.read()
    with io.open(os.path.join(root, DATA_PATH), encoding="utf-8") as f:
        data = json.load(f)
    with io.open(os.path.join(root, SEED_PATH), encoding="utf-8") as f:
        seed = f.read()

    if "def refresh_lessons(" in seed:
        print("Already applied. Nothing to do.")
        return
    if '"3.84.0"' not in init:
        sys.exit("ABORT: not at v3.84.0.")

    problems = []
    for key, lessons in NEW_LESSONS.items():
        if key not in data:
            problems.append(f"  unknown module key {key}")
            continue
        old = data[key]["lessons"]
        if len(lessons) != len(old):
            problems.append(f"  {key}: {len(lessons)} lessons vs existing {len(old)}")
            continue
        for a, b in zip(lessons, old):
            if a["title"] != b["title"]:
                problems.append(f"  {key}: title drift '{a['title']}' vs '{b['title']}'")
        for a, b in zip(lessons, old):
            if len(a["html"]) < len(b["html"]):
                problems.append(f"  {key}/'{a['title']}': SHORTER than existing")
    if set(NEW_LESSONS) != set(data):
        problems.append(f"  module coverage mismatch: {sorted(set(data) - set(NEW_LESSONS))}")
    if "ERPNext" in json.dumps(NEW_LESSONS):
        problems.append("  ERPNext branding leakage")
    if problems:
        print("ABORT — not clean:")
        print("\n".join(problems))
        sys.exit(1)

    old_chars = sum(len(l["html"]) for m in data.values() for l in m["lessons"])
    new_chars = sum(len(l["html"]) for m in NEW_LESSONS.values() for l in m)
    print(f"Content check passed: all 8 modules, titles stable, {old_chars:,} -> {new_chars:,} chars ({new_chars/old_chars:.1f}x).")

    if CHECK_ONLY:
        print("--check given; no files written.")
        return

    for key, lessons in NEW_LESSONS.items():
        data[key]["lessons"] = lessons
    with io.open(os.path.join(root, DATA_PATH), "w", encoding="utf-8") as f:
        json.dump(data, f, indent=1, ensure_ascii=False)
        f.write("\n")
    with io.open(os.path.join(root, SEED_PATH), "w", encoding="utf-8") as f:
        f.write(seed + REFRESH_SRC)
    with io.open(os.path.join(root, INIT), "w", encoding="utf-8") as f:
        f.write(init.replace('"3.84.0"', '"3.85.0"'))
    print("  data: all 33 lessons rewritten · seeder: +refresh_lessons()")
    print("wrote __init__.py -> 3.85.0")


if __name__ == "__main__":
    main()
