#!/usr/bin/env python3
"""Add check questions to the ZhiftERP Selling track.

Fourth of the seven role tracks. Content written and product-accurate; no
checks across 73 chapters. push_lesson_checks already covers sales_pro by name.

Same guard as the previous three: refuses the whole run on any duplicate
against the exam bank, any repeated check, any rationale under 40 characters,
any option count other than four, or any chapter of a touched module left
without checks.

Run from the app package directory:  python3 add_sales_checks.py
"""

import collections
import io
import json
import random
import re
import sys

DATA = "academy_sales_pro_data.json"
CHECK_ONLY = "--check" in sys.argv
FORCE = "--force" in sys.argv

C = lambda q, opts, ans, why: {"q": q, "opts": opts, "ans": ans, "why": why}


CHECKS = {
"sales_orders": {
 0: [
  C("Everything before the Sales Order was offer. Everything after it:",
    ["Renegotiates it", "Executes it",
     "Confirms it", "Reports on it"], 1,
    "The Delivery Notes ship against it and the invoices bill against it."),
  C("The Sales Order is the agreement to supply these items, quantities and prices on this schedule and:",
    ["This margin", "These payment terms",
     "This territory", "This warehouse"], 1,
    "Which is why the payment schedule sits on the order rather than being decided at invoicing."),
  C("The module covers the field walk, the commitment mechanics, the schedule, amendments, payments and:",
    ["The invoice run", "The order book reads",
     "The pipeline", "The delivery notes"], 1,
    "The open orders being the business's committed future.")],
 1: [
  C("On a converted order the quotation's header values carry, and the verification rule:",
    ["Is waived", "Stands either way",
     "Applies only to rows", "Applies at submission"], 1,
    "The header is read before the rows, whether the order was converted or created fresh."),
  C("The customer's own purchase order number is entered because:",
    ["The system requires it", "It prints on the delivery and invoice, and their payables function matches on it",
     "It sets the terms", "It drives the schedule"], 1,
    "Enterprise and institutional customers almost always issue one."),
  C("Selecting the customer pulls currency, price list, payment terms template, addresses and:",
    ["The credit limit", "The contact",
     "The territory target", "The delivery schedule"], 1,
    "Module 1's machinery arriving on the document.")],
 2: [
  C("A submitted order row's undelivered quantity enters:",
    ["Actual Qty", "Reserved Qty on the item-warehouse Bin",
     "Ordered Qty", "Indented Qty"], 1,
    "Which is what makes projected quantity fall and the reorder arithmetic see the commitment."),
  C("Because projected quantity falls on submission, the next order's preparer:",
    ["Sees more stock", "Does not promise the same stock twice",
     "Must check manually", "Waits for delivery"], 1,
    "Availability questions answer against projected rather than actual, so the same stock is not promised twice."),
  C("Stale-order reservations matter because they:",
    ["Inflate the order book", "Hold stock against commitments that are no longer real",
     "Delay invoicing", "Affect margin"], 1,
    "Reservation hygiene is what keeps projected quantity meaningful.")],
 3: [
  C("A multi-wave order is expressed by:",
    ["The header date", "Per-row delivery dates",
     "Separate orders", "A delivery schedule doctype"], 1,
    "The rows state the schedule; the header carries the final date."),
  C("Row delivery dates must state the real plan agreed with the customer because:",
    ["The customer sees them", "Every planning read computes from them",
     "They set the invoice date", "They drive reservation"], 1,
    "A placeholder schedule produces overdue flags on rows the customer never expected."),
  C("100 units on the first date and 100 on the second is expressed as:",
    ["Two orders", "The same item split across rows with different dates",
     "One row with a note", "A blanket order"], 1,
    "The mechanism for every schedule shape is the per-row date.")],
 4: [
  C("A concession appearing on an amendment that was never approved:",
    ["Becomes approved by the amendment", "Does not become approved",
     "Requires a new order", "Is approved by submission"], 1,
    "Commercial changes re-enter the deviation ladder at the band the change belongs to."),
  C("A quantity increase on an amendment runs again:",
    ["The tax computation", "The credit and availability checks",
     "The approval ladder only", "The schedule read"], 1,
    "More commitment means the same checks that governed the original."),
  C("A wave already picked or shipped:",
    ["Un-ships by amendment", "Does not un-ship by amendment",
     "Is cancelled separately", "Reverses the reservation"], 1,
    "Decreases release reservation and are checked against work already done.")],
 5: [
  C("The enterprise milestone pattern described is:",
    ["100% on invoice", "An advance at order, a portion on delivery, a retention at completion",
     "Half on order, half on delivery", "Monthly instalments"], 1,
    "The 50/40/10 shape, with each row's portion and timing as the negotiated agreement states."),
  C("The payment schedule rows are generated by:",
    ["Manual entry", "The Payment Terms Template",
     "The invoice", "The credit ladder"], 1,
    "Which is why terms come from templates rather than being typed."),
  C("The invoices raised later:",
    ["Set their own due dates", "Follow the schedule the order states",
     "Use the customer default", "Are dated at delivery"], 1,
    "The order states when money is due, and the invoice inherits it.")],
 6: [
  C("The order book carries value, age, %delivered, %billed and:",
    ["The margin", "The next scheduled date",
     "The territory", "The salesperson"], 1,
    "Committed revenue, its schedule and its execution state in one report."),
  C("The weekly order book pass works the list:",
    ["Oldest first", "Top-down by value",
     "By customer", "By delivery date"], 1,
    "The largest commitments' next actions confirmed on calendar."),
  C("An overdue delivery row is resolved as delivered, expedited or:",
    ["Cancelled", "Re-dated by documented amendment",
     "Written off", "Escalated"], 1,
    "Each with its cause and its action rather than left flagged.")],
 7: [
  C("The BizRetail order was created from:",
    ["The original quotation", "Round two, the final accepted version",
     "The customer's PO", "A fresh draft"], 1,
    "Checked row-by-row against it before submission."),
  C("The 4% concession carried onto the order applied to:",
    ["All equipment lines", "Terminals only, per the approval's named scope",
     "The service lines", "The whole order"], 1,
    "Scanners and printers remained at list, because that is what was approved."),
  C("Alongside the purchase order number, what was attached to the order was:",
    ["The pick list", "The acceptance document",
     "The credit check", "The delivery plan"], 1,
    "The evidence of what the customer accepted, filed with the commitment.")],
 8: [
  C("Commitments made in calls that the order does not state are corrected by:",
    ["Honouring them informally", "Amending the real agreement onto the order with its approvals",
     "A side letter", "A note on the file"], 1,
    "The order states the whole agreement, and the confirmation puts it in the customer's hands."),
  C("One optimistic header date on multi-wave reality produces:",
    ["A simpler order", "Overdue flags on rows the customer never expected",
     "Faster invoicing", "A reservation error"], 1,
    "And planning reads computing from fiction."),
  C("The prevention for the promise beside the order is:",
    ["More approvals", "The order stating the whole agreement, confirmed to the customer",
     "Recording calls", "A stricter ladder"], 1,
    "Anything not on the document is not part of the agreement the business will execute.")],
},
"delivery": {
 0: [
  C("The Delivery Note is described as the document of:",
    ["Invoicing", "Custody transfer",
     "Reservation", "Fulfilment planning"], 1,
    "Before submission the goods are the business's; after it they are not."),
  C("A Delivery Note records which items, in what quantities, from which warehouse, to which address and:",
    ["At what price", "On which date",
     "Under which order", "By which vehicle"], 1,
    "The physical despatch, recorded as a document."),
  C("The module covers the field walk, picking and despatch, partial and wave deliveries, the postings, returns and:",
    ["The invoice run", "The delivery reads",
     "The order book", "The pick lists"], 1,
    "The reads on their cadences: pending acknowledgment, delivered-not-billed, and the overdue rows.")],
 1: [
  C("On a multi-site customer, each Delivery Note selects:",
    ["The head office address", "The receiving branch's address",
     "The billing address", "The default address"], 1,
    "It prints on the despatch paperwork the driver carries."),
  C("The billing address on a Delivery Note:",
    ["Changes per despatch", "Does not change per despatch",
     "Is optional", "Is the shipping address"], 1,
    "It carries for the invoice linkage, so the goods can go to a branch while the bill goes to head office."),
  C("The Delivery Note should be created:",
    ["Fresh, then linked", "From the Sales Order, so rows, rates and references carry",
     "From the invoice", "By import"], 1,
    "Inheritance rather than re-keying, exactly as with the order.")],
 2: [
  C("A picker who knows the order well is about to work from memory. They should instead work from:",
    ["The Sales Order screen", "The pick list",
     "The customer's PO", "The delivery note draft"], 1,
    "The list states the order reference, items, quantities in their units, locations and identity requirements."),
  C("For batch-controlled items, the picked batch is:",
    ["Chosen at submission", "The batch recorded",
     "Allocated automatically", "Confirmed at invoicing"], 1,
    "Identity is captured at pick rather than reconstructed afterwards."),
  C("Part-quantities are counted:",
    ["By carton", "In units, per the unit-column discipline",
     "By estimate", "At the vehicle"], 1,
    "The same rule the counting module applies on the shelf.")],
 3: [
  C("Partial delivery is:",
    ["An exception requiring approval", "A normal mechanism",
     "Permitted below a tolerance", "A scheduling failure"], 1,
    "The schedule's waves and stock timing both use it."),
  C("The requirement on each partial despatch is that it is:",
    ["Approved separately", "A complete document in itself — verified, identified, acknowledged",
     "Under the tolerance", "Invoiced immediately"], 1,
    "Partial in quantity does not mean partial in discipline."),
  C("When a Delivery Note row carries less than the order row's quantity, the remainder:",
    ["Is cancelled", "Stays open on the order row with its date",
     "Moves to a new order", "Is written off"], 1,
    "Subsequent Delivery Notes draw it until the row completes.")],
 4: [
  C("The stock leaves the source warehouse at:",
    ["The selling price", "The item's valuation rate",
     "A typed rate", "The order rate"], 1,
    "The valuation method's rate, never a rate typed on the document — the cost side is not a selling decision."),
  C("For controlled items, submission records the delivered identities, which is what makes possible:",
    ["The invoice", "The recall trace and the warranty record",
     "The reservation release", "The margin calculation"], 1,
    "Batch and serial balances fall per the bundle."),
  C("The custody transfer is effective:",
    ["On acknowledgment", "At submission",
     "On invoicing", "At despatch"], 1,
    "After which the stock is no longer the business's.")],
 5: [
  C("A customer returns a serialised unit whose number does not appear on the original delivery. You should:",
    ["Accept it and note the difference", "Stop the line and investigate",
     "Record it as found stock", "Refer it back to the customer"], 1,
    "The business confirms it is receiving back what it shipped."),
  C("The return is recorded on a Delivery Note marked Is Return, created from:",
    ["A blank document", "The original Delivery Note",
     "The Sales Order", "The invoice"], 1,
    "So the rows, rates and references carry."),
  C("Returned quantities are counted at receipt against:",
    ["The original delivery", "The customer's return advice",
     "The order", "The invoice"], 1,
    "What physically came back, checked rather than accepted.")],
 6: [
  C("A Delivery Note is submitted but no signed copy has come back. What the business is carrying is:",
    ["A billing delay", "An unproven custody transfer",
     "A stock discrepancy", "A scheduling problem"], 1,
    "The pending-acknowledgment read keeps the exposure short."),
  C("The delivered-not-billed read feeds:",
    ["The order book", "The invoicing run",
     "The pick lists", "The returns lane"], 1,
    "Submitted deliveries whose invoicing has not followed within the cadence, cleared at each invoicing run."),
  C("The pending-acknowledgment read is measured by:",
    ["The number of deliveries", "The file's completeness",
     "The value outstanding", "The customer's response rate"], 1,
    "Each submitted note chased to its proof of delivery.")],
 7: [
  C("Wave one of the BizRetail rollout covered:",
    ["All twelve branches", "The first five branches",
     "Three branches", "The Lagos branches"], 1,
    "Each receiving one terminal, one scanner and one printer."),
  C("Five pick lists were issued for one vehicle because:",
    ["The system requires one per note", "Each branch is a separate despatch to a separate address",
     "The items differ", "The dates differ"], 1,
    "One route, five destinations, five documents."),
  C("The serials on the equipment had been captured:",
    ["At despatch", "At receipt from the supplier",
     "At the customer", "At invoicing"], 1,
    "Which is what made identity capture at pick a verification rather than a data-entry exercise.")],
 8: [
  C("Goods leaving with the Delivery Note still in draft produces:",
    ["A billing delay", "Stock records showing goods the shelf no longer holds",
     "A reservation error", "An acknowledgment gap"], 1,
    "And the custody transfer unrecorded at the moment it happened."),
  C("A Delivery Note differing from the physical load means the difference is inherited by:",
    ["The invoice only", "Both the customer's receipt and the stock records",
     "The order", "The reservation"], 1,
    "Which is why the second-person verification happens before submission."),
  C("The prevention for the mismatched document is picking against the list, identity captured at pick and:",
    ["Manager approval", "The second-person verification before submission",
     "A recount at the vehicle", "Customer confirmation"], 1,
    "Three steps, each with an owner and a record.")],
},
"taxes_invoicing": {
 0: [
  C("In the selling sequence, the Sales Order reserves stock, the Delivery Note deducts it and posts cost, and the Sales Invoice:",
    ["Reserves again", "Posts revenue, tax and the receivable",
     "Confirms delivery", "Releases reservation"], 1,
    "Each document posting its own effects in a fixed order."),
  C("This module prepares the machinery the Sales Invoice depends on:",
    ["The credit ladder", "The tax configuration, pricing postures and discount governance",
     "The delivery schedule", "The order book"], 1,
    "Configuration set before the document rather than decided on it."),
  C("The standing rule of the tax and invoicing module is that tax on a document is:",
    ["Negotiable", "Computed by configuration, never edited by hand",
     "Set per customer", "Confirmed by the accountant"], 1,
    "The accountant owns the configuration, so a document showing an unexpected tax is a configuration question rather than an editing one.")],
 1: [
  C("Your invoice adds ₦75 of VAT to a ₦1,000 sale. That ₦75 belongs to:",
    ["The business, as revenue", "The government, held as a liability until remitted",
     "The customer, as a credit", "Cost of sales"], 1,
    "It is collected on the state's behalf and remitted with the periodic VAT return."),
  C("Nigerian VAT stands at:",
    ["5%", "7.5%",
     "10%", "12.5%"], 1,
    "Added on top of the net price, or contained within it under the inclusive posture."),
  C("At invoicing, the tax row posts to:",
    ["Revenue", "The VAT output liability account",
     "A receivable", "A suspense account"], 1,
    "Which is where every charged naira of VAT begins its liability path.")],
 2: [
  C("The standard base for a VAT row is Type:",
    ["Actual", "On Net Total",
     "On Previous Row Amount", "On Item Quantity"], 1,
    "Actual is used for flat charges such as a delivery fee."),
  C("A Sales Taxes and Charges Template is:",
    ["A single rate", "A named, ordered set of rows, each computing one charge",
     "A customer attribute", "A report"], 1,
    "Documents select the template and its rows compute the tax section."),
  C("A flat delivery fee on a document is expressed as a row of Type:",
    ["On Net Total", "Actual",
     "On Previous Row Total", "Percentage"], 1,
    "Its own row in the template rather than an adjustment to the tax.")],
 3: [
  C("An Item Tax Template overrides the document template's rate:",
    ["For the whole document", "For that row only",
     "For the customer", "For the item group"], 1,
    "Standard rows compute at 7.5% while exempt rows compute at 0% on the same document."),
  C("The design means one document can serve:",
    ["One tax treatment", "Any basket, including exempt medicines beside standard-rated cosmetics",
     "One item group", "One customer class"], 1,
    "The tax section totals the per-line results."),
  C("On a mixed document, the tax section shows:",
    ["The document rate applied throughout", "The per-line results totalled",
     "An average rate", "Two separate templates"], 1,
    "Which is what makes a mixed pharmacy invoice computable at all.")],
 4: [
  C("A rate of ₦1,075 entered under the inclusive posture at 7.5% yields net:",
    ["₦1,075", "₦1,000",
     "₦994", "₦1,156"], 1,
    "The extraction divides by one plus the rate."),
  C("Exclusive pricing is described as the posture for:",
    ["Counter retail", "Business-to-business trade",
     "Exempt goods", "Export sales"], 1,
    "Trade customers, procurement offices and input-credit accounting all work in net prices."),
  C("Under exclusive pricing a rate of ₦1,000 at 7.5% produces a document total of:",
    ["₦1,000", "₦1,075",
     "₦925", "₦1,750"], 1,
    "Net ₦1,000, VAT ₦75, gross ₦1,075 — the tax adds on top of the entered rate rather than being extracted from it.")],
 5: [
  C("A class that always pays less should have:",
    ["A permanent document discount", "A list, or a list-derived arrangement",
     "A pricing rule per order", "A negotiated rate"], 1,
    "The price list is the standing class price, maintained through the governed update."),
  C("Policy that repeats belongs in:",
    ["Document discounts", "A Pricing Rule",
     "The customer record", "The terms template"], 1,
    "So that it applies uniformly and expires on its date."),
  C("The three instruments that reduce a price below list are the price list, the Pricing Rule and:",
    ["The credit limit", "The document discount",
     "The payment term", "The tax template"], 1,
    "Each with its own holder and its own record.")],
 6: [
  C("A movement of around 30% across three periods on any dimension is:",
    ["A figure to note", "A change to investigate and explain",
     "Normal variation", "A reporting artefact"], 1,
    "A customer's volume, a group's revenue, or a territory's mix."),
  C("Sales Analytics can cut revenue by the dimensions that:",
    ["The report defines", "The registers disciplined — customer, item, group, territory",
     "The user chooses freely", "The accountant sets"], 1,
    "Which is the payoff of the classification work in modules 1 and 2."),
  C("The standing read on Sales Analytics is:",
    ["The current period's total", "The trend read — current against prior periods on each major dimension",
     "The top customers", "The margin ranking"], 1,
    "Configuration is confirmed by reading, and a trend across periods shows movement that a single period cannot.")],
 7: [
  C("HealthTrade's one variant template beyond the standard was:",
    ["A trade template", "The delivery-charge template, adding an Actual freight row",
     "An exempt template", "An export template"], 1,
    "Entered in the configuration register with its purpose."),
  C("Template-write permission was confirmed as:",
    ["The sales manager's", "The accountant's role only",
     "Shared", "The sysadmin's"], 1,
    "Tax is computed by configuration, and the configuration has one owner."),
  C("The item treatments were applied:",
    ["Item by item", "By class, per the ruling table",
     "At document time", "By customer group"], 1,
    "The exempt pharmaceutical lines against the standard-rated general goods.")],
 8: [
  C("Tax amounts adjusted on documents to match expectations produce:",
    ["A faster close", "A return that disagrees with the configuration",
     "Rounding accuracy", "A template gap"], 1,
    "The configuration question is resolved at the template rather than on the document."),
  C("An exempt item computing at 7.5%, corrected by hand on the document, means:",
    ["The error is resolved", "The next document repeats the error",
     "The template is wrong", "The customer is misclassified"], 1,
    "The correction belongs on the item's classification, not on the invoice."),
  C("The prevention for the hand-edited tax row is tax computed by configuration only and:",
    ["Monthly review", "Template-write permission held per the matrix",
     "Approval on edits", "Rounding tolerance"], 1,
    "Tax computed by configuration only, with write permission on the templates held by one named role.")],
},
"sales_invoice": {
 0: [
  C("The Sales Invoice is described as:",
    ["The customer's copy", "The accounting event of the sale",
     "A collection instrument", "The order's confirmation"], 1,
    "It posts the revenue, the output VAT and the receivable."),
  C("On the document timeline the invoice is:",
    ["The first document", "The third — after the order reserves and the delivery deducts",
     "Concurrent with delivery", "Optional"], 1,
    "Each document posting its own effects in sequence."),
  C("The module covers the field walk, the creation paths, the postings, payments, credit notes, receivables and:",
    ["The order book", "Collections",
     "The pipeline", "The pricing rules"], 1,
    "Ending with collections, run as a written four-gear procedure rather than as a series of reminders.")],
 1: [
  C("A customer record missing its TIN where e-invoicing operates is corrected:",
    ["On the invoice", "At the record, before the invoice submits",
     "At month-end", "By the accountant"], 1,
    "The gate requirement enforced at the point it matters."),
  C("The due date on an invoice computes from:",
    ["The posting date plus thirty days", "The payment terms template",
     "The customer's request", "The delivery date"], 1,
    "The schedule rows the template generates."),
  C("The posting date is:",
    ["When the invoice was printed", "The date the revenue and receivable post",
     "The delivery date", "The due date"], 1,
    "Set honestly per the standing date rule.")],
 2: [
  C("The standard trade path creates the invoice from:",
    ["The Sales Order", "The Delivery Note",
     "A blank document", "The quotation"], 1,
    "Billing performance: the invoice draws the delivered rows, %billed advances, and the delivered-not-billed list clears."),
  C("The milestone path creates the invoice from:",
    ["The Delivery Note", "The Sales Order",
     "The payment entry", "The blanket order"], 1,
    "Drawing the portion the payment schedule makes due."),
  C("Invoicing from the Delivery Note bills:",
    ["The order quantity", "Exactly what shipped",
     "The scheduled portion", "The agreed total"], 1,
    "And the row references carry both documents.")],
 3: [
  C("Submission debits the customer's account for the gross total, which increases:",
    ["The revenue", "The outstanding balance the credit limit checks against",
     "The reserved quantity", "The margin"], 1,
    "The customer now owes the invoice on its due date."),
  C("Revenue credits per:",
    ["The document total", "The item defaults, per the accountant's design",
     "The price list", "The customer group"], 1,
    "The income accounts credit per the item defaults, and the revenue is recognised on the posting date."),
  C("Where cost posted at delivery, the period's margin reads:",
    ["Only at invoicing", "Complete, with cost and revenue both landed",
     "Net of tax", "At the order date"], 1,
    "Which is why cut-off needs both the deliveries and the invoices in.")],
 4: [
  C("The allocation table should follow:",
    ["Oldest invoice first, always", "The customer's remittance advice",
     "The largest invoice first", "The due date order"], 1,
    "The customer states what they are paying, and the allocation records it."),
  C("A Payment Entry records that money arrived; what records what it pays is:",
    ["The reference field", "The allocation",
     "The posting date", "The bank account"], 1,
    "An unallocated receipt leaves the invoices it should have cleared still ageing."),
  C("The reference captured on a Payment Entry is:",
    ["The invoice number", "The customer's transfer reference or instrument number",
     "The order number", "The bank's batch"], 1,
    "Which is what lets the payment be matched at the bank and by the customer.")],
 5: [
  C("A credit note reverses the receivable, debits revenue and:",
    ["Leaves VAT unchanged", "Reverses the VAT output for the credited value",
     "Posts to a discount account", "Adjusts the cost"], 1,
    "The return's tax leaves the period's accumulation, keeping the VAT return aligned with commercial reality."),
  C("A credit note is a Sales Invoice marked Is Return, created against:",
    ["The delivery note", "The original invoice",
     "The order", "A new document"], 1,
    "Created against the original invoice so the reference carries and the credit is tied to what it reduces."),
  C("The standing case for a credit note is:",
    ["A pricing correction", "The return lane completing its money side",
     "A goodwill gesture", "A write-off"], 1,
    "The return Delivery Note recorded what came back; the credit note settles the claim.")],
 6: [
  C("The aging report's reliability depends on due dates from templates, invoices from documents, payments allocated and:",
    ["Statements sent", "Credits settled",
     "Limits enforced", "Territories assigned"], 1,
    "Every discipline in the track feeding one report."),
  C("The aging is read weekly by collections and monthly by:",
    ["The accountant", "The owner, with the receivables summary",
     "The sales team", "The auditor"], 1,
    "Weekly for the working list, monthly for the owner alongside the receivables summary."),
  C("Open invoices are bucketed by age against:",
    ["The posting date", "The due date",
     "The delivery date", "The order date"], 1,
    "Which is why a typed due date corrupts the whole report.")],
 7: [
  C("Gear one is the pre-due contact, triggered at:",
    ["The due date", "7 days before due, above the policy's value threshold",
     "30 days overdue", "First reminder"], 1,
    "Queries and missing-document problems are resolved before the due date instead of becoming the reason for lateness after it."),
  C("Every collections contact is recorded with date, person and:",
    ["Amount", "Outcome",
     "Next gear", "Approval"], 1,
    "The collections file is part of the account's record."),
  C("The purpose of the pre-due contact is to confirm the invoice is with them, complete, approved for payment and:",
    ["That payment is scheduled", "That any query is surfaced now",
     "The balance agreed", "The terms accepted"], 1,
    "Surfacing a query before the due date changes what lateness means.")],
 8: [
  C("BizRetail's 50% advance was claimed at order and:",
    ["Invoiced at delivery", "Funded before the work queue took the order",
     "Deferred to completion", "Netted at the end"], 1,
    "The Payment Entry recorded the advance, which then sat identified on the ledger awaiting allocation."),
  C("The advance sat on the ledger:",
    ["As revenue", "Identified, awaiting allocation",
     "As an unallocated mystery", "Netted against receivables"], 1,
    "Which is what makes the later allocation to the delivery-portion invoice straightforward."),
  C("The delivery-portion invoice followed:",
    ["The order schedule alone", "Wave one's submitted delivery",
     "The customer's request", "The month end"], 1,
    "Five branches, fifteen units, acknowledged before the claim was raised.")],
 9: [
  C("Due dates entered by hand cause the aging to compute from:",
    ["The invoice date", "Improvised dates",
     "The template", "The delivery date"], 1,
    "And the terms decisions to be bypassed entirely."),
  C("Direct invoices for what should be order-and-delivery flows produce:",
    ["Faster billing", "Quantities disagreeing with despatches, and claims with no references",
     "Simpler records", "Better margins"], 1,
    "The chain is reconstructed and the invoice corrected through the credit lane."),
  C("The prevention for billing beside the documents is the three-path rule and:",
    ["Manager approval", "The monthly direct-invoice read",
     "A tighter credit limit", "Order enforcement only"], 1,
    "So the exceptions stay exceptional and visible.")],
},
"advanced": {
 0: [
  C("The advanced instruments extend the standard flow with bundles, blanket orders, attribution and:",
    ["Credit control", "The Selling Settings that enforce the track's disciplines in configuration",
     "The pricing rules", "The collections gears"], 1,
    "Closing with the consolidated selling calendar."),
  C("The module closes by assembling:",
    ["The settings register", "The operating rhythm modules 1 to 7 built",
     "The commission read", "The bundle register"], 1,
    "The reads and their cadences, in one place."),
  C("Selling Settings matter because they turn the track's rules from:",
    ["Policy into training", "Procedure into enforcement",
     "Configuration into policy", "Reads into reports"], 1,
    "An invoice without an order refused by configuration rather than by discipline.")],
 1: [
  C("The bundle's parent item is created with Maintain Stock:",
    ["On", "Off",
     "Set per company", "As for any item"], 1,
    "The bundle is a commercial unit, not a warehoused product."),
  C("What physically ships when a bundle sells is:",
    ["The parent item", "The component items in the child table",
     "A kit item", "Whatever is picked"], 1,
    "The parent is the selling line; the components are the stocked products."),
  C("The bundle's price is set:",
    ["By summing components", "On the price lists, like any item",
     "As a discount rule", "Per document"], 1,
    "Its code and name follow the register conventions.")],
 2: [
  C("Forty shelves and six scanners support how many bundles of four shelves and one scanner?",
    ["Ten", "Six",
     "Forty", "Four"], 1,
    "Sellable bundles is the minimum across components of available divided by quantity per bundle."),
  C("A bundle wave is at risk if:",
    ["The parent is unpriced", "Any component is short",
     "The bundle price changed", "The order is large"], 1,
    "The planning read flags the constraining component."),
  C("A bundle's availability is:",
    ["Held as its own stock", "Computed from its components",
     "Set manually", "Reserved at order"], 1,
    "A bundle holds no stock of its own, so its availability is only ever the minimum its components allow.")],
 3: [
  C("A Blanket Order posts nothing, reserves nothing and ships nothing. Its function is to:",
    ["Commit the customer", "Hold the negotiated terms for the period",
     "Reserve capacity", "Schedule deliveries"], 1,
    "Agreed quantities and rates over a period, drawn in parts."),
  C("The same Blanket Order doctype serves:",
    ["Selling only", "Selling and purchasing arrangements",
     "One customer at a time", "One item class"], 1,
    "One doctype for both sides of the business, with the order type distinguishing a selling arrangement from a buying one."),
  C("The blanket order's items table carries each item with its agreed total quantity and:",
    ["Its delivery date", "Its agreed rate for the period",
     "Its reserved quantity", "Its warehouse"], 1,
    "Which is what call-offs then draw against.")],
 4: [
  C("Sales team contribution percentages on a document must sum to:",
    ["Any total", "One hundred",
     "The commission rate", "The number of persons"], 1,
    "Attribution belongs to the commitment and carries from order to invoice."),
  C("Attribution is set at:",
    ["The invoice", "The order",
     "The delivery", "The quotation"], 1,
    "And carries forward, so the commitment and the credit for it stay together."),
  C("The Sales Person tree should mirror the real structure and keep to:",
    ["Two levels", "Three levels or fewer",
     "One level", "As many as the org chart"], 1,
    "The standing tree rules, applied to selling responsibility.")],
 5: [
  C("Sales Order required, switched on, means an invoice without an order is:",
    ["Warned", "Refused by configuration except for the named direct cases",
     "Approved by a manager", "Logged"], 1,
    "The setting turns the three-path rule from procedure into enforcement."),
  C("Delivery Note required, switched on, enforces:",
    ["Stock accuracy", "Performance before claim",
     "Order sequencing", "Acknowledgment"], 1,
    "Billing must follow despatch for stock items."),
  C("Per-case exceptions to those settings are admitted only through:",
    ["Manager override", "The roles and lanes the site configures, with a control register row",
     "A note on the invoice", "The accountant"], 1,
    "An exception that leaves no record is not an exception, it is a gap.")],
 6: [
  C("The weekly fifteen-minute read covers open quotations, overdue rows, delivered-not-billed, discounts and:",
    ["The margin report", "The trend read",
     "The order book", "The aging"], 1,
    "Five checks in fifteen minutes, closing with a written note so the week leaves a record."),
  C("The invoicing run's two worklists are the due milestones and:",
    ["The aging", "Delivered-not-billed",
     "Open orders", "Pending acknowledgments"], 1,
    "Delivered-not-billed and due milestones, both worked to zero so nothing shipped or scheduled goes unclaimed."),
  C("Payments should be recorded:",
    ["Weekly", "Same-day, and allocated per remittances",
     "At the month end", "On the statement date"], 1,
    "An unrecorded payment is a customer chased for money they have already sent.")],
 7: [
  C("The Pharmacy Display Pack's ₦361,000 price against ₦450,000 of component list is a reduction of:",
    ["9.8%", "19.8%",
     "29.8%", "5%"], 1,
    "Recorded with its arithmetic in the bundle register entry."),
  C("The pack comprises four display shelves and:",
    ["Two scanners", "One barcode scanner",
     "One printer", "One terminal"], 1,
    "The child table stating the components with their quantities per bundle."),
  C("PHARM-DISPLAY-PACK was created as a sales item with:",
    ["Maintain Stock on", "Maintain Stock off",
     "Batch tracking", "A serial number"], 1,
    "The parent is commercial; the components are the stock.")],
 8: [
  C("A bundle parent created as a stock item produces:",
    ["Correct reservations", "Phantom balances nobody can count",
     "Accurate availability", "A pricing error"], 1,
    "Reconciliations then chase an item that never physically exists."),
  C("Packages sold as component lists at improvised prices produce:",
    ["Flexible pricing", "Inconsistent package pricing across documents, and an invoice that does not state what the customer bought",
     "Simpler picking", "Better margins"], 1,
    "The bundle exists so the package is one decided thing."),
  C("The prevention for the stocked bundle is Maintain Stock off on parents and:",
    ["A monthly count", "The boundary test at definition",
     "A naming convention", "Approval on creation"], 1,
    "Deciding at definition whether the thing is a commercial unit or a warehoused product.")],
},
"customers": {
 0: [
  C("Every selling document names a customer and pulls from that record:",
    ["Only the address", "The price list, payment terms, credit limit, tax treatment and addresses",
     "The item prices only", "The territory"], 1,
    "Which is why the record's quality determines every document raised against it."),
  C("The Customer record's fields are described as behaviour rather than description because they:",
    ["Print on documents", "Drive what every downstream document does",
     "Feed the reports", "Set the naming"], 1,
    "A wrong group prices documents until somebody finds it."),
  C("The selling foundations module covers the customer master, the trees, contacts and addresses, credit and terms, the gate and:",
    ["The invoice", "The customer data reads",
     "The pipeline", "The territory targets"], 1,
    "Each read on its own cadence, keeping the register true.")],
 1: [
  C("The Customer Group is described as a working field rather than a label because:",
    ["Reports aggregate by it", "Default price lists and payment terms can derive from it",
     "It is mandatory", "It drives the naming series"], 1,
    "A misclassification therefore prices documents rather than merely mis-sorting a report."),
  C("Customer Type — Company or Individual — drives:",
    ["The credit limit", "Which tax and compliance fields apply, and how the record reads in reporting",
     "The price list", "The territory"], 1,
    "A classification with consequences rather than a description."),
  C("The Customer Name is entered:",
    ["As convenient, and tidied later", "Once, correctly, at the gate",
     "By the sales person", "From the TIN register"], 1,
    "It prints on every document and statement, and correcting it after documents exist is remediation.")],
 2: [
  C("A chain customer in Ibadan and a retail counter in Ibadan share a territory and differ in:",
    ["Address", "Group",
     "Terms", "Currency"], 1,
    "The two trees are independent classifications answering different questions."),
  C("Designing one tree to answer both the commercial and geographic questions produces a tree that:",
    ["Is simpler to maintain", "Answers neither cleanly",
     "Duplicates records", "Cannot be reported on"], 1,
    "Group answers what kind of buyer; Territory answers where and whose responsibility."),
  C("Territories drive:",
    ["Pricing", "Sales reporting and targets",
     "Payment terms", "Tax treatment"], 1,
    "While groups drive price list and terms defaults, and the receivables and margin aggregations.")],
 3: [
  C("Statements and collections should go to:",
    ["The company address", "A named accounts payable contact",
     "The primary contact", "The buyer"], 1,
    "Role-specific contacts exist so the right person receives the right document."),
  C("A Contact record can link to:",
    ["One customer only", "Several parties",
     "One address", "One document type"], 1,
    "One record per person, with the customer's primary contact marked."),
  C("Contacts and addresses are:",
    ["Fields on the Customer", "Separate records linked to the customer",
     "Child tables", "Held per document"], 1,
    "Which is what makes the multi-site pattern possible.")],
 4: [
  C("Terms typed per invoice rather than from a template:",
    ["Save time", "Bypass the decision and corrupt the aging",
     "Are permitted below a value", "Require approval"], 1,
    "The receivables aging computes from the due dates the template sets."),
  C("Payment Terms Templates are described as:",
    ["One option among several", "The only lawful source of terms",
     "A convenience", "A reporting device"], 1,
    "The ladder decides which template a customer receives."),
  C("Credit is described as:",
    ["A sales tool", "The business lending money to its customers",
     "A pricing decision", "A terms preference"], 1,
    "Which is why it runs on a written, owner-approved ladder rather than on conversation.")],
 5: [
  C("Every field walked at creation is quick to complete then and:",
    ["Optional afterwards", "Costly to correct after documents exist",
     "Set by default", "Reviewed monthly"], 1,
    "The gate is fifteen minutes that ends the wrong-group, missing-TIN and undecided-terms cases."),
  C("The first step of the gate checklist is:",
    ["Setting the group", "The duplicate check",
     "The credit decision", "The TIN capture"], 1,
    "Searched by name fragments, phone, email and TIN before creation."),
  C("A missing TIN discovered late:",
    ["Is corrected at leisure", "Blocks invoicing at month-end",
     "Affects reporting only", "Delays delivery"], 1,
    "Which is one of the three cases the gate exists to prevent.")],
 6: [
  C("A duplicate customer means credit is checked against:",
    ["The larger balance", "Partial exposure",
     "The combined limit", "The wrong territory"], 1,
    "And the customer disputes statements that show only part of their history."),
  C("The duplicate-candidate read runs:",
    ["Weekly", "Monthly",
     "Quarterly", "At the gate only"], 1,
    "Near-misses are noted so the next gate search finds them."),
  C("The classification read samples group and territory against the definitions:",
    ["Monthly", "Quarterly",
     "Annually", "At onboarding"], 1,
    "With regrades applied and fragmenting nodes flagged for the structural review.")],
 7: [
  C("The first question asked at the chain pharmacy's gate was:",
    ["How many branches?", "Who pays?",
     "What volume?", "Which territory?"], 1,
    "The answer decides whether it is one customer with many shipping addresses or thirty child customers."),
  C("Head office paying for all branches produced:",
    ["Thirty customer records", "One Customer record, one receivables balance, one credit limit",
     "One record per state", "A parent-child structure"], 1,
    "One receivables balance and one credit limit, with the thirty branches as shipping addresses on that record."),
  C("The rejected alternative — thirty child customers — was:",
    ["Not considered", "Recorded as considered and rejected",
     "Deferred", "Implemented partially"], 1,
    "Recording the rejected option is what makes the decision answerable later.")],
 8: [
  C("Terms set in conversation and limits typed per invoice produce:",
    ["Flexibility", "An aging computed from improvised due dates",
     "Faster onboarding", "Better relationships"], 1,
    "Terms only from templates, credit only from the ladder, and the monthly changes read."),
  C("The correction for the duplicate customer is:",
    ["Disabling one record", "The merge remediation with documents re-pointed",
     "A note on both", "Deleting the newer"], 1,
    "Prevention is the gate's duplicate search."),
  C("Credit without a decision is corrected by applying templates and:",
    ["Reducing all limits", "Filing the ladder's decisions retroactively where defensible",
     "Suspending credit", "Referring to the accountant"], 1,
    "With limits reviewed rather than left at whatever was typed.")],
},
"items_prices": {
 0: [
  C("The Item is one record read by several functions, each owning its section. The selling side owns:",
    ["The stock flags", "The commercial fields, units, prices and the tax classification",
     "The account derivations", "The identity settings"], 1,
    "Inventory owns the stock flags and identity; Accounts owns the account derivations."),
  C("Items reach this module having been created through:",
    ["The selling gate", "The Inventory track's gate",
     "The price list", "A data import"], 1,
    "One record, several owners, one creation route."),
  C("The module's standing rule is that a price is:",
    ["Negotiable per document", "A decision with a record, never a figure typed at document time",
     "Set per customer", "Reviewed annually"], 1,
    "Document-time rates are reserved for approved negotiated cases only.")],
 1: [
  C("Item codes are described as:",
    ["Editable as products evolve", "Permanent",
     "Set per price list", "Generated automatically"], 1,
    "A product whose code must change is retired and re-created, because documents reference codes forever."),
  C("The Item Name should read:",
    ["As the warehouse knows it", "As customers should read it on documents",
     "In the internal shorthand", "By code"], 1,
    "Complete, consistently formatted, without internal abbreviations customers will not recognise."),
  C("PARA-500 as an item code illustrates a convention that is:",
    ["Descriptive and long", "Short, unique and structured",
     "Sequential", "Group-derived"], 1,
    "The code is the register's handle: printed, keyed, typed and scanned daily.")],
 2: [
  C("Carton-12 and Ctn-12 created as separate UOM records:",
    ["Are equivalent", "Split conversion history",
     "Are merged automatically", "Affect only reporting"], 1,
    "A new unit is a register decision, not a per-item improvisation."),
  C("The conversion factor states:",
    ["The price ratio", "How many stock units one alternative unit contains",
     "The pack weight", "The reorder multiple"], 1,
    "Every document row entered in an alternative unit converts by it."),
  C("The carton rate and the conversion factor are:",
    ["Maintained separately", "Maintained together",
     "Derived from each other", "Set once at creation"], 1,
    "A factor changed without the rate produces a carton priced as though it held a different quantity.")],
 3: [
  C("The price lists and the Customer Group tree are described as:",
    ["Independent designs", "The same design read from two sides",
     "Alternatives", "Linked by territory"], 1,
    "Standard Selling for the counter, Trade for chains, institutions and distributors."),
  C("A Price List record carries the name, the currency and:",
    ["The customer group", "The Selling flag",
     "The validity", "The territory"], 1,
    "Buying lists belong to the Procurement track."),
  C("A price list is best described as:",
    ["A discount schedule", "A named pricing context",
     "A report", "A customer attribute"], 1,
    "A set of Item Prices applying to the customers who resolve to it.")],
 4: [
  C("Where one list prices units and cartons separately, the standing shape is:",
    ["One row with a conversion", "Two rows on the same list, each applying when the document row's unit matches",
     "Two price lists", "A Pricing Rule"], 1,
    "One row per item per list is the base case; per-UoM rows extend it."),
  C("An Item Price is:",
    ["A customer's agreed rate", "One item's price on one list",
     "A document default", "A pricing rule"], 1,
    "With the UOM, minimum quantity and validity dates where the site uses them."),
  C("Prices are changed by:",
    ["Editing at document time", "The governed update procedure",
     "The sales person", "Bulk import only"], 1,
    "A price is a decision with a record, so changing one is a governed update rather than an edit at document time.")],
 5: [
  C("Quantity breaks and class discounts should be configured as:",
    ["Document discounts", "Pricing Rules",
     "Separate price lists", "Customer defaults"], 1,
    "Structured price behaviour is configured, not typed."),
  C("A Pricing Rule's scope makes it as narrow or broad as the decision, covering item, item group or brand and:",
    ["Warehouse", "Customer, customer group or territory",
     "Currency", "Payment terms"], 1,
    "One item for one customer group, or a whole group for all trade customers."),
  C("Quantity thresholds on a Pricing Rule are:",
    ["Advisory", "The quantity-break mechanism",
     "Validation only", "Reporting filters"], 1,
    "Minimum and maximum quantity or amount, with validity dates.")],
 6: [
  C("For a Nigerian pharmaceutical register the item tax classification is live because:",
    ["Rates change often", "Many pharmaceutical items are VAT-exempt while general goods are standard-rated",
     "Exports differ", "Wholesale differs from retail"], 1,
    "The item-side field states each product's treatment once."),
  C("The document's tax computation combines the document-level template with:",
    ["The customer's group", "The item tax template",
     "The territory", "The price list"], 1,
    "Which is why the classification lives on the item rather than being decided per document."),
  C("The item tax template may sit on the item or be:",
    ["Typed per document", "Derived from its item group per the site's design",
     "Set per customer", "Chosen at invoicing"], 1,
    "Either way it is stated once rather than decided repeatedly.")],
 7: [
  C("HealthTrade's two-channel reality was configured on one record by:",
    ["Two item codes", "A stock unit of Unit plus a conversion table carrying Carton-12",
     "Two price lists only", "A pricing rule"], 1,
    "One record, two units, with rates on the list for each."),
  C("Item groups were assigned per the tree, with Analgesics sitting under:",
    ["General Goods", "Pharmaceuticals",
     "Trade", "Standard Selling"], 1,
    "The reporting tree, applied at the commercial walk."),
  C("The commercial walk closed with:",
    ["A price review", "The draft-row verification per class sample",
     "A margin read", "The tax audit"], 1,
    "Confirming that a document row actually behaves as the configuration intends.")],
 8: [
  C("Rates entered at document time because the list has no price produce:",
    ["Faster quoting", "Margins varying by operator, and disputes with no reference",
     "A pricing rule gap", "Reporting errors only"], 1,
    "The completeness read finds the missing prices and the update procedure loads them."),
  C("A selling-side duplicate item record splits:",
    ["Pricing only", "Stock and sales history",
     "The tax treatment", "The unit conversions"], 1,
    "The one-record principle: the commercial fields are a section of the existing record, not a new one."),
  C("A sales person wants to type a rate directly on a document. That is legitimate only when:",
    ["The customer negotiated it", "It is an approved negotiated case",
     "The customer is trade", "The volume is large"], 1,
    "Every sales item is priced on its group's list.")],
},
"quotations": {
 0: [
  C("Everything downstream — the order, the deliveries, the invoices — inherits:",
    ["The customer's terms", "What the quotation states",
     "The price list", "The delivery schedule"], 1,
    "Which is why the offer is built from the registers rather than composed freehand."),
  C("A Quotation is the business's written offer: these items, these quantities, these prices, these terms, and:",
    ["This delivery date", "Valid until this date",
     "This payment method", "This territory"], 1,
    "The validity is part of the offer rather than an administrative field."),
  C("Building the offer from the registers rather than freehand means:",
    ["Faster preparation", "The customer, items, units, prices and terms all come from records that were decided elsewhere",
     "Fewer fields", "Automatic approval"], 1,
    "Composition is where unreviewed commitments enter.")],
 1: [
  C("Selecting the customer on a Quotation pulls the price list, currency, terms default, addresses and contact. That pre-fill is:",
    ["A starting suggestion to retype", "The intended behaviour — verify rather than retype",
     "Editable freely", "Applied at submission"], 1,
    "Retyping what the register already decided is how documents drift from the master."),
  C("Valid Till is described as:",
    ["A formality", "A commitment boundary",
     "A reporting field", "An optional date"], 1,
    "Set per the policy's standard window, shortened for volatile-cost items, never left blank."),
  C("A Quotation may be addressed to a Customer or:",
    ["A Territory", "A Lead",
     "A Contact", "A Group"], 1,
    "Where the site quotes prospects before they enter the customer register.")],
 2: [
  C("The rates on a draft quotation have pre-filled from the registers. What the preparer does next is:",
    ["Compose the offer", "Verify them",
     "Negotiate them", "Send for approval"], 1,
    "The right list resolved, the expected rule fired, the units matching the rates."),
  C("Deviations from the pre-filled rates are:",
    ["A sales judgement", "Decisions with owners, per the written ladder",
     "Permitted within reason", "Recorded afterwards"], 1,
    "The ladder's bands decide who may approve what."),
  C("Seeing the 50-unit row show its break confirms:",
    ["The customer qualifies", "The expected Pricing Rule fired",
     "The list is correct", "The margin holds"], 1,
    "Verification means checking the machinery did what the configuration says it should.")],
 3: [
  C("A customer accepting on the last valid day:",
    ["May be re-quoted", "Gets the quoted terms",
     "Requires approval", "Receives current prices"], 1,
    "That is what issuing a dated offer means, and the pricing accounts for the window's exposure."),
  C("Acceptance after expiry triggers:",
    ["Honouring the offer", "A re-quote at current prices",
     "An approval request", "A validity extension"], 1,
    "Expired offers are not resurrected by editing."),
  C("Volatile-cost lines such as imported goods in a moving exchange environment carry:",
    ["The standard window", "The short window the policy names",
     "No validity", "A renegotiation clause"], 1,
    "The validity window is priced exposure, so a moving cost base gets a shorter window rather than a higher price.")],
 4: [
  C("Typed terms are:",
    ["Faster", "Unreviewed terms",
     "Permitted for small offers", "Equivalent to templates"], 1,
    "And unreviewed terms are what the business discovers it agreed to during a dispute."),
  C("Terms and Conditions templates carry the standing text and are:",
    ["Editable per quotation", "Owned, with the register row naming the owner",
     "Optional", "Set per customer"], 1,
    "The owner or counsel who approved the wording."),
  C("Templates are the only source of terms text, selected on the document rather than:",
    ["Attached separately", "Typed per quotation",
     "Referenced by number", "Sent afterwards"], 1,
    "Which is what makes them reviewable at all.")],
 5: [
  C("The follow-up cadence runs the issue-week contact, the mid-validity follow-up and:",
    ["A monthly call", "The pre-expiry contact",
     "A quarterly review", "The conversion check"], 1,
    "Each contact noted on the document or its thread, so any colleague can pick up the negotiation."),
  C("Every quotation should end in:",
    ["An order", "A marked state",
     "A revision", "An expiry"], 1,
    "Ordered, lost, expired — marked when known, so the pipeline is true."),
  C("The open-quotations read runs:",
    ["Daily", "Weekly",
     "Monthly", "At expiry"], 1,
    "By age and days-to-validity, with expiry hygiene folded in.")],
 6: [
  C("The Sales Order should be created from:",
    ["The original quotation", "The final revision, verified against the negotiation file",
     "A fresh draft", "The customer's purchase order"], 1,
    "Creating from a superseded version ships the wrong round's prices."),
  C("Create > Sales Order carries the party, rows, rates, taxes and terms into the draft, which ensures:",
    ["Faster entry", "The order states exactly what the customer accepted, without re-keying errors",
     "Automatic approval", "Correct scheduling"], 1,
    "Inheritance rather than transcription, so the order cannot differ from the accepted offer by a typing error."),
  C("The control against building an order from a superseded quotation version is:",
    ["The system's versioning", "The negotiation file's version thread",
     "The validity date", "The approval ladder"], 1,
    "Which is why the file is kept as the offer is revised.")],
 7: [
  C("The BizRetail offer covered 12 terminals, 12 scanners, 12 printers plus:",
    ["Maintenance", "Installation and training",
     "Financing", "Warranty extension"], 1,
    "Service lines drawn from the register alongside the equipment lines."),
  C("The BizRetail cycle ran:",
    ["One round in a week", "Three weeks and two rounds",
     "Two months", "A single revision"], 1,
    "Which is what the revision procedure and the negotiation file exist to handle."),
  C("The quotation drafted from the registers with rates pre-filling from:",
    ["Standard Selling", "The Trade list",
     "A negotiated list", "The customer's last order"], 1,
    "The customer's group resolved the list before any rate was considered.")],
 8: [
  C("Offers issued under the margin floor by composition rather than approval are corrected by:",
    ["Accepting them", "Running the deviations read and applying the ladder retroactively where defensible",
     "Raising the floor", "Re-issuing all offers"], 1,
    "And re-quoting where the deviation cannot be defended."),
  C("A sent quotation edited in place produces:",
    ["A cleaner record", "The customer and the business holding disagreeing documents",
     "A version conflict", "An approval gap"], 1,
    "The dispute is then conducted from two versions."),
  C("The prevention for the below-floor offer is the pre-fill as default, the ladder for every deviation and:",
    ["Manager sign-off", "The margin read before issue",
     "A tighter validity", "Customer approval"], 1,
    "Checked before the offer leaves rather than after it is accepted.")],
},
}


def rebalance(items, seed):
    n = len(items)
    base, extra = divmod(n, 4)
    slots = []
    for i in range(4):
        slots += [i] * (base + (1 if i < extra else 0))
    random.Random(seed).shuffle(slots)
    for it, target in zip(items, slots):
        cur = it["ans"]
        if cur == target:
            continue
        shift = (target - cur) % 4
        it["opts"] = it["opts"][-shift:] + it["opts"][:-shift]
        it["ans"] = target
    return items


def main():
    data = json.load(io.open(DATA, encoding="utf-8"))

    for mod_key, chapters in CHECKS.items():
        if mod_key not in data:
            sys.exit("ABORT: module %r not in %s" % (mod_key, DATA))
        flat = [c for _i, ch in sorted(chapters.items()) for c in ch]
        rebalance(flat, "sales:%s:checks" % mod_key)

    added = skipped = 0
    problems = []
    for mod_key, chapters in CHECKS.items():
        lessons = data[mod_key]["lessons"]
        missing = [i + 1 for i in range(len(lessons)) if i not in chapters]
        if missing:
            problems.append("%s: no checks for chapter(s) %s" % (mod_key, missing))
        bank = {re.sub(r"[^a-z0-9 ]", "", q["q"].lower()).strip()
                for q in data[mod_key].get("questions") or []}
        seen = set()
        for idx, checks in sorted(chapters.items()):
            if idx >= len(lessons):
                sys.exit("ABORT: %s has no chapter %d" % (mod_key, idx + 1))
            if len(checks) != 3:
                problems.append("%s ch%d has %d checks" % (mod_key, idx + 1, len(checks)))
            for c in checks:
                norm = re.sub(r"[^a-z0-9 ]", "", c["q"].lower()).strip()
                if norm in bank:
                    problems.append("duplicates exam question: %s" % c["q"][:58])
                if norm in seen:
                    problems.append("duplicate check: %s" % c["q"][:58])
                seen.add(norm)
                if len(c.get("why") or "") < 40:
                    problems.append("weak rationale: %s" % c["q"][:50])
                if len(c["opts"]) != 4:
                    problems.append("not 4 options: %s" % c["q"][:50])
            l = lessons[idx]
            if l.get("checks") and not FORCE:
                skipped += 1
                continue
            if not CHECK_ONLY:
                l["checks"] = [dict(c, sort=i) for i, c in enumerate(checks)]
            added += len(checks)

    if problems:
        print("ABORT — %d problem(s):" % len(problems))
        for p in problems:
            print("   %s" % p)
        sys.exit(1)

    print("checks to add: %d | chapters already done: %d" % (added, skipped))
    if CHECK_ONLY:
        print("--check given; nothing written.")
        return

    with io.open(DATA, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write("\n")

    chs = sum(len(m["lessons"]) for m in data.values())
    done = sum(1 for m in data.values() for l in m["lessons"] if l.get("checks"))
    tot = sum(len(l.get("checks") or []) for m in data.values() for l in m["lessons"])
    print("track now: %d of %d chapters have checks, %d checks total" % (done, chs, tot))
    sp = collections.Counter(c["ans"] for m in data.values()
                             for l in m["lessons"] for c in (l.get("checks") or []))
    print("answer spread:", dict(sorted(sp.items())))


if __name__ == "__main__":
    main()
