#!/usr/bin/env python3
"""Add check questions to the ZhiftERP Inventory track.

Same repair as the Accounts and ZhiftPOS tracks. The content is written and
product-accurate; there are no checks at all across 72 chapters.

academy_repair.push_lesson_checks already covers inventory_pro by name and
matches by position within a lesson, so nothing in the seeder needs changing.

Checks are derived strictly from what each chapter states. The guard below
refuses the whole run if any check duplicates the 280-question exam bank,
repeats another check, carries a rationale under 40 characters, or does not
have four options.

Idempotent, with --force to refresh a chapter that already has checks.

Run from the app package directory:  python3 add_inventory_checks.py
"""

import collections
import io
import json
import random
import re
import sys

DATA = "academy_inventory_pro_data.json"
CHECK_ONLY = "--check" in sys.argv
FORCE = "--force" in sys.argv

C = lambda q, opts, ans, why: {"q": q, "opts": opts, "ans": ans, "why": why}


CHECKS = {
"counting": {
 0: [
  C("A count variance should be understood as:",
    ["Evidence of theft", "Information — a missing document, a process gap, or a loss",
     "An accounting adjustment", "A keeper's failure"], 1,
    "The records say what should be on the shelf; the count establishes what is."),
  C("Counting is described as not being:",
    ["A regular routine", "Suspicion of the keeper",
     "A management task", "Comparable across sites"], 1,
    "It is how the difference between record and reality is discovered while it is still small."),
  C("The Stock Reconciliation posts as of:",
    ["The date it is entered", "The count's cut-off moment",
     "The period end", "The approval date"], 1,
    "The instant at which the physical truth and the records are being compared.")],
 1: [
  C("An opening rate wrong by a factor at go-live:",
    ["Is corrected at the first count", "Propagates into every valuation after it",
     "Affects only that item's balance", "Reverses on the next receipt"], 1,
    "Which is why opening rates are checked against recent purchase documents before submission."),
  C("The Opening Stock purpose is used:",
    ["At every count", "At go-live, to load opening balances",
     "For cycle counts", "After a remediation"], 1,
    "Stock Reconciliation is the standing purpose for aligning records to a count."),
  C("Before ever submitting a Stock Reconciliation you should know:",
    ["Who counted it", "What submission posts",
     "The variance threshold", "The approval route"], 1,
    "It writes both stock and value, and the posting cannot be undone by editing.")],
 2: [
  C("Full counts should be scheduled:",
    ["At month end", "Clear of peak trading, and announced to operations",
     "Unannounced", "On the cycle calendar"], 1,
    "The count competes with the work otherwise; spot counts are unannounced by design."),
  C("A count's quality is decided:",
    ["On the floor", "Before anyone touches a shelf",
     "At entry", "In the variance review"], 1,
    "Scope, schedule, cut-off, freeze and blind sheets are all preparation."),
  C("The cut-off exists because the count compares shelf to records:",
    ["Over the count window", "As of one moment",
     "At period end", "Per warehouse"], 1,
    "Either movements stop for the window, or documents in flight are completed or excluded explicitly.")],
 3: [
  C("A count written in strips against a carton line is:",
    ["A rounding difference", "The error the briefing warned about",
     "Acceptable if noted", "Corrected at entry"], 1,
    "The unit column governs, and verifying it is exactly the checker's job."),
  C("Sealed cartons may be counted as cartons:",
    ["Always, to save time", "Only where the policy accepts seal integrity for that class",
     "Never", "Where the supplier is trusted"], 1,
    "High-value and regulated classes open per the sampling rule."),
  C("The rule for part cartons is that they are:",
    ["Estimated", "Opened and counted in units",
     "Counted as one", "Excluded"], 1,
    "Count, do not infer — a part carton estimated from its appearance is a guess written into the record as a fact.")],
 4: [
  C("The person entering count sheets should:",
    ["Be the counter, for accuracy", "Not be the counter of the lines being entered",
     "Be the keeper", "Be the coordinator"], 1,
    "The separation completing its loop, and entry works from signed sheets only."),
  C("Unlisted stock found during a count enters as:",
    ["An adjustment line", "Its own list, for the investigation lanes",
     "A new item", "A transfer"], 1,
    "Stock found that the records did not expect is a different question from stock missing."),
  C("Entry for full counts is checked line-for-line by:",
    ["The counter", "A second person",
     "The system", "The keeper"], 1,
    "Sampled for cycle counts per the policy.")],
 5: [
  C("The first step in investigating a variance that survives recount is:",
    ["Interview the keeper", "The document sweep",
     "A second count", "The valuation check"], 1,
    "Most real variances are paperwork, so the sweep finds the cause before anybody is asked to explain a loss."),
  C("The unposted movement means the despatch physically gone but:",
    ["Counted twice", "Never entered",
     "Entered late", "Entered at the wrong rate"], 1,
    "The item's recent physical events are walked against its ledger."),
  C("Stock counted at neither end because it is correctly in transit is verified by:",
    ["A recount", "The count's scope arithmetic",
     "The keeper's statement", "The transit report alone"], 1,
    "The boundary check confirms it sits where the documents say rather than having gone missing.")],
 6: [
  C("ABC classification ranks a warehouse's items by:",
    ["Unit cost", "Annual consumption value",
     "Movement frequency", "Shelf space"], 1,
    "Or stock value where consumption data is young."),
  C("The classification should be treated as:",
    ["A one-time label", "A living output of the data, reviewed twice a year",
     "An item attribute set at creation", "A purchasing decision"], 1,
    "Stored as the item's class field or the count calendar's list."),
  C("Cycle counting converts the annual count's mountain into:",
    ["A quarterly exercise", "A daily routine",
     "A sampling programme", "A monthly close task"], 1,
    "With a frequency per class and an accuracy metric.")],
 7: [
  C("HealthTrade's opening reconciliation found one line whose rate disagreed with its latest invoice cost, and it was:",
    ["Adjusted at the first count", "Corrected from the document before the figure could propagate",
     "Accepted with a note", "Referred to the auditor"], 1,
    "The opening then posted with the accountant's sign-off."),
  C("The first ABC classification found that 62 A items carried:",
    ["Half the value", "71% of the value at Central",
     "A third of the value", "Most of the lines"], 1,
    "Computed from six months of consumption data."),
  C("The opening baseline check ran:",
    ["After submission", "Before submission",
     "At the first cycle count", "At year end"], 1,
    "Opening valuation rates sampled against recent purchase documents.")],
 8: [
  C("Reconciliations posted straight from the variance report convert:",
    ["Time into savings", "Information into silence",
     "Variances into adjustments", "Counts into records"], 1,
    "And the same variances recur because their causes were never found."),
  C("Counts that confirm the records with suspicious perfection indicate:",
    ["Excellent control", "Sheets carrying system quantities",
     "A well-trained team", "A stable warehouse"], 1,
    "The correction is to run the next count blind and compare the results honestly."),
  C("The prevention for adjustment before investigation is:",
    ["Manager approval", "The threshold ladder, with investigation references on every banded row",
     "A second count", "Monthly reconciliation"], 1,
    "Before submission rather than afterwards.")],
},
"valuation": {
 0: [
  C("Stock value moves with the stock — in at receipt, between warehouses on transfers, and out to:",
    ["The balance sheet", "Cost of goods sold at delivery",
     "The variance account", "The margin report"], 1,
    "Or to an expense account where it is issued rather than sold."),
  C("Valuation errors are described as:",
    ["Self-correcting", "Silent",
     "Rare", "Caught at the count"], 1,
    "Which is why the rate-error reads exist to make them loud at the low-cost moment."),
  C("Every unit of stock in the records carries:",
    ["A standard cost", "A value",
     "A supplier reference", "A count date"], 1,
    "And that value is what the accounts and the margin both rest on.")],
 1: [
  C("An entry inserted into the past changes:",
    ["Only its own row", "Every running figure after it",
     "The item's average only", "Nothing until reposted manually"], 1,
    "The ledger sorts by posting date and time, which is why the honest-date rule matters here."),
  C("Every Stock Ledger Entry row traces to its document:",
    ["Through the voucher report", "In one click",
     "By reconciliation", "Via the Bin"], 1,
    "A ledger question is answered by opening the document that wrote the row."),
  C("The Stock Ledger report is read filtered to:",
    ["One warehouse", "One item and one warehouse",
     "One voucher type", "One period"], 1,
    "Together the columns tell that pair's complete value story.")],
 2: [
  C("Under Moving Average, each receipt pulls the carrying rate toward its own rate:",
    ["Equally", "In proportion to its size",
     "Only if higher", "At period end"], 1,
    "New rate equals existing value plus incoming value, over the combined quantity."),
  C("Under Moving Average, an outgoing row changes:",
    ["The rate", "The quantity and value together, at the current average",
     "The rate and the quantity", "Nothing until close"], 1,
    "The rate moves on receipts, not on issues."),
  C("Changing an item's valuation method is:",
    ["A configuration preference", "A governed event",
     "Done annually", "Automatic on reclassification"], 1,
    "One decision per item, and changes are not made casually.")],
 3: [
  C("Freight, clearing, duties and insurance are added to stock value through:",
    ["A Journal Entry", "The Landed Cost Voucher",
     "The Purchase Invoice", "A Stock Reconciliation"], 1,
    "They are part of what the stock cost, not a period expense."),
  C("The three-way match is also a valuation control because the invoice price it verifies is:",
    ["The margin base", "The rate the stock will carry",
     "The supplier's claim", "The reorder trigger"], 1,
    "The Purchase Receipt is the main door through which rates enter."),
  C("Every valuation error walked through:",
    ["The count", "One of the four doors where rates are born",
     "The repost queue", "A journal"], 1,
    "Which is why each door has its own discipline.")],
 4: [
  C("A Material Issue posts stock down and:",
    ["Cost of goods sold up", "The row's Difference Account up",
     "The received-not-invoiced liability up", "A variance account up"], 1,
    "Damage and consumption go to their own accounts — the account is part of the reason."),
  C("A Purchase Receipt posts the stock account up and:",
    ["Creditors up", "The received-not-invoiced liability up",
     "Cost of goods sold up", "The difference account up"], 1,
    "The goods are in stock before the bill arrives, so the accrual holds the liability until the Purchase Invoice clears it."),
  C("The monthly tie-out proves that:",
    ["The count agrees with the Bin", "The stock ledger and the accounts still agree",
     "Rates match invoices", "Transit is empty"], 1,
    "Under perpetual inventory the stock documents post their own accounting, and the two ledgers must still meet.")],
 5: [
  C("A backdated receipt triggers a repost because under Moving Average:",
    ["The item is revalued once", "Every subsequent average is different",
     "Only that row changes", "The queue is rebuilt"], 1,
    "Under FIFO the queue's composition changes instead."),
  C("The repost runs as:",
    ["An immediate recalculation", "A background job queued per affected item-warehouse scope",
     "A month-end process", "A manual utility"], 1,
    "Which is why the queue is something to watch rather than assume."),
  C("Reposts are triggered by backdated stock documents and:",
    ["Counts", "Cancellations",
     "Transfers", "Landed cost entry only"], 1,
    "Anything that changes what the balance cost from a past date forward.")],
 6: [
  C("₦96,000 entered against a ₦9,600 history should be:",
    ["Posted and reviewed later", "A stopped line and a question",
     "Approved by the buyer", "Averaged out"], 1,
    "A data-entry slip, a unit confusion, or a real price event worth confirming."),
  C("The last-paid drift eye runs:",
    ["Monthly", "At entry, on every receipt",
     "At the count", "In the tie-out"], 1,
    "The check takes five seconds per line and stops the damage at its cheapest moment."),
  C("The carton rate typed against a unit line belongs to:",
    ["The rounding errors", "The UoM family of errors",
     "The supplier's pricing", "The landed cost adjustments"], 1,
    "Which is one of the three explanations the stopped line is checked against.")],
 7: [
  C("HealthTrade's Allow Negative Stock had been switched on in week two of the original go-live to:",
    ["Support consignment", "Silence posting errors",
     "Speed up counting", "Permit backdating"], 1,
    "And was left on for four years, producing a tail of negative balances."),
  C("The negative-stock remediation was run as:",
    ["A configuration change", "A project with the accountant and the sysadmin",
     "A month-end task", "An automatic repost"], 1,
    "The negative balances listed and each one traced rather than switched off underneath them."),
  C("The valuation review at the start of the year found two inherited conditions: negative stock enabled, and:",
    ["Missing landed costs", "A scatter of strange valuation rates",
     "An untied stock account", "Unposted reposts"], 1,
    "Both inherited from the pre-discipline era, and each had been producing damage quietly for four years.")],
 8: [
  C("A receipt rate an order of magnitude off history pollutes the average until:",
    ["The next count", "A review notices",
     "Period close", "The repost runs"], 1,
    "Issues are mis-priced throughout, which is why the entry check is the prevention."),
  C("Import costs sitting in period expenses mean stock is:",
    ["Overvalued", "Carried at bare invoice price",
     "Correctly valued", "Valued at standard cost"], 1,
    "Margins are then mis-timed, and the correction is Landed Cost Vouchers for the affected receipts."),
  C("The consignment rule prevents freight being expensed by requiring the voucher:",
    ["At month end", "Per consignment",
     "Before the invoice", "At the count"], 1,
    "So the cost lands on the stock it belongs to rather than in the period it was paid.")],
},
"branch_network": {
 0: [
  C("This module is the earlier machinery operating as:",
    ["A separate system", "A network",
     "A reporting layer", "A branch process"], 1,
    "Warehouses with custody, transfers through transit, identity on movements, counts, and value following documents."),
  C("The standing design is:",
    ["Branch-to-branch", "Hub and spoke",
     "Central purchasing only", "Independent sites"], 1,
    "With replenishment running from the hub on a weekly cycle."),
  C("Branch demand reaches Central as:",
    ["Phone calls and messages", "Documents",
     "Reorder alerts only", "Sales forecasts"], 1,
    "The Material Request and the reorder levels that raise requests automatically.")],
 1: [
  C("The Material Request purpose used for a branch's ask is:",
    ["Purchase", "Material Transfer",
     "Material Issue", "Manufacture"], 1,
    "Purchase-purpose requests belong to the Procurement track."),
  C("Submitting a Material Request makes the demand:",
    ["Approved", "Visible and countable",
     "Reserved", "Committed to despatch"], 1,
    "The replenishment run works from submitted requests."),
  C("Reorder levels exist so that:",
    ["Branches order less", "Requests raise automatically",
     "Transit is reduced", "Counts are scheduled"], 1,
    "Alongside the branches' own consolidated asks.")],
 2: [
  C("The replenishment run's inputs include the requests, the sell-through view, the hub's availability and:",
    ["The count calendar", "The transit state",
     "The reorder levels", "The branch P&L"], 1,
    "So the run does not re-send what is already on the road."),
  C("Each request line is reviewed against the branch's sell-through and:",
    ["Its last order", "Its current projected quantity",
     "The hub's reorder level", "The item's class"], 1,
    "Producing an approved, adjusted or held outcome."),
  C("The replenishment cycle runs:",
    ["Daily", "Weekly",
     "On request", "Monthly"], 1,
    "With the inputs assembled in about thirty minutes.")],
 3: [
  C("Central cannot fill every approved ask this week. The basis for deciding who gets what should be:",
    ["The stock manager's judgement on the day", "A written rule, documented and communicated",
     "First request, first served", "The largest branch first"], 1,
    "Agreed with the owner before the first scarce week."),
  C("The first rule in application order is:",
    ["Pro-rata on sell-through", "The essential floor",
     "Largest branch first", "Equal split"], 1,
    "For items the policy marks essential, from the data plus the business's own judgement."),
  C("Allocation becomes a decision when:",
    ["Any request exceeds a threshold", "The approved asks total more than Central's available quantity",
     "A branch complains", "Transit is full"], 1,
    "A short shipment, a demand spike, or a late import.")],
 4: [
  C("You are opening a new branch and its shelves need filling. The stock should arrive by:",
    ["A Stock Reconciliation", "Transfer from the hub",
     "Direct purchase to the branch", "An opening entry"], 1,
    "Never by reconciliation — the stock arrives with documents behind it."),
  C("The first ninety days of a new branch run on:",
    ["The standard weekly cycle", "A weekly review cycle, because opening estimates differ from actual demand",
     "Monthly review", "The hub's judgement"], 1,
    "The range was built from a comparable branch and trimmed, and the plan says so."),
  C("Before any stock moves to a new branch, the prerequisites include the warehouses, the custody names, the permissions and:",
    ["The first count", "The POS profile pointing at the branch stock room",
     "The reorder levels", "The lateral rules"], 1,
    "Plus the Item Defaults reviewed for the site.")],
 5: [
  C("Laterals between branches are approved at:",
    ["The sending branch", "The centre",
     "Either end", "The receiving branch"], 1,
    "Because the network view — what is in transit, what the run is about to despatch — lives at Central."),
  C("A well-meant lateral can:",
    ["Bypass the count", "Cross a replenishment already moving",
     "Break valuation", "Skip identity capture"], 1,
    "Which is why the proposal comes from the branches and the approval does not."),
  C("Laterals are executed as:",
    ["Direct issues", "Standard transfers, two-step through transit where sites are apart",
     "Reconciliations", "Sales between branches"], 1,
    "With identity on the rows, exactly like any other movement.")],
 6: [
  C("The module's most frequently used figure is:",
    ["Stock value per branch", "The sell-through read",
     "The transit balance", "Days of cover"], 1,
    "It feeds the replenishment review, the allocation arithmetic, the new-branch cycle and the rebalancing proposals."),
  C("The sell-through percentage compares units sold against:",
    ["Units ordered", "Units stocked across the window",
     "Units received", "The reorder level"], 1,
    "Which is what makes it comparable between branches of different sizes."),
  C("The sell-through read covers:",
    ["The current week", "An eight-week movement view",
     "The year to date", "The last cycle"], 1,
    "Eight weeks per item per branch, which is long enough to show a trend and short enough to reflect current demand.")],
 7: [
  C("Akure's opening range was built from:",
    ["Central's full catalogue", "Ibadan's stocking list and sell-through, trimmed for the smaller catchment",
     "The supplier's recommendation", "An equal split"], 1,
    "With the plan stating that these are estimates the first-cycle review will correct."),
  C("The opening transfer to Akure was despatched as:",
    ["A single reconciliation", "Standard two-step transfers, batches on every row",
     "A direct issue", "A purchase to the branch"], 1,
    "Received at Akure against the despatch rows."),
  C("Before any stock moved to Akure, the warehouses:",
    ["Were created that week", "Already stood in the tree from the original design",
     "Were merged from Ibadan", "Were created by the branch"], 1,
    "With the keeper and deputy named and permissions scoped.")],
 8: [
  C("Branches double-ordering what is already in transit is caused by requests reasoning on:",
    ["Projected quantity", "The shelf",
     "Sell-through", "The reorder level"], 1,
    "The prevention is reasoning on shelf minus commitments plus incoming."),
  C("The padded ask — requests inflated to hedge against short allocation — is prevented by:",
    ["Approval thresholds", "The allocation arithmetic being communicated, so hedging gains nothing",
     "Reducing reorder levels", "Capping requests"], 1,
    "Pro-rata on sell-through means an inflated ask does not produce a larger share."),
  C("Padded asks damage the network by:",
    ["Delaying despatch", "Polluting the run's data and eroding trust in both directions",
     "Increasing transit", "Raising stock value"], 1,
    "The correction is adjustments with reasons rather than silent trimming.")],
},
"stock_health": {
 0: [
  C("Modules 1 to 6 keep the records accurate. This module reads them to ask:",
    ["Whether the counts agree", "Whether the stock itself is in good condition as an investment",
     "Whether valuation is correct", "Whether custody holds"], 1,
    "Stock that does not move ties up money that could be working elsewhere."),
  C("Stock health is a question about the stock rather than the records, which means a branch can have:",
    ["Poor records and healthy stock", "Perfect records and unhealthy stock",
     "Neither independently", "Health only where records are accurate"], 1,
    "Accuracy is the precondition for the reads; it is not the same as the stock being any good."),
  C("The module's output is a monthly:",
    ["Variance report", "Health page",
     "Aging schedule", "Reorder list"], 1,
    "Carrying the turns, the aging profile and the decisions attached to them.")],
 1: [
  C("You hold 40 units of an item received across three deliveries. The Stock Ageing report ages them using:",
    ["The item's creation date", "The receipt dates of the quantities still on hand",
     "The most recent movement", "The last count date"], 1,
    "The earliest-in quantities age first, consistent with the receipt-queue arithmetic."),
  C("The standing band structure for a trading business is 0-30, 31-60, 61-90 and:",
    ["Over 120", "Over 90",
     "Over 180", "Over 365"], 1,
    "The policy sets the bands, and for a pharmaceutical distributor they are read alongside the expiry horizons."),
  C("For a pharmaceutical distributor the aging bands should be read alongside:",
    ["The reorder levels", "The expiry horizons",
     "The ABC classes", "The turns figure"], 1,
    "Age and remaining shelf life are different risks and both bear on the same stock.")],
 2: [
  C("The movement classification defines 'negligible' numerically so that the classification is:",
    ["Defensible to the auditor", "Computed rather than judged",
     "Comparable to the ABC class", "Reviewable quarterly"], 1,
    "The policy sets the number and the read applies it."),
  C("The standing window for movement classification is:",
    ["Eight weeks", "Two quarters",
     "One year", "The current month"], 1,
    "Fast, slow and dead are computed from consumption across it."),
  C("Value ranking and movement speed are combined because:",
    ["Both are computed monthly", "They are different measurements, and priorities need both",
     "ABC is unreliable alone", "Value follows movement"], 1,
    "A high-value dead item and a low-value dead item need different responses.")],
 3: [
  C("Sell-through states units sold across the window as a percentage of:",
    ["Units ordered", "Units available across the window — opening stock plus receipts",
     "Units received", "The reorder level"], 1,
    "Which is what makes it comparable across items, sites and periods."),
  C("An item selling at one site and not another is described in the network view as:",
    ["Uniform low", "Divergent",
     "Seasonal", "Misclassified"], 1,
    "And divergence is what makes rebalancing the first dead-stock lane."),
  C("An item with uniform low sell-through across every site is:",
    ["A rebalancing candidate", "A range or pricing question",
     "A supply problem", "A count error"], 1,
    "Moving it between sites cannot help when nowhere is selling it.")],
 4: [
  C("The first lane in preference order for dead stock is:",
    ["Markdown", "Rebalancing",
     "Return to supplier", "Write-off"], 1,
    "It recovers full price and costs a transfer, which is why it comes first."),
  C("Each dead-stock lane is executed:",
    ["By management decision", "By document",
     "At the monthly review only", "By the branch holding it"], 1,
    "Five lanes, assigned at the monthly review, each leaving a record."),
  C("Markdown sits below rebalancing in the preference order because it:",
    ["Is slower", "Gives up margin the other lane would have recovered",
     "Requires approval", "Affects other sites"], 1,
    "Discounting at the site where stock aged, while another site sells it at full price, is the error the order prevents.")],
 5: [
  C("A reorder level set for a fast item whose demand is slowing will:",
    ["Adjust automatically", "Keep ordering fast-item quantities until somebody corrects it",
     "Stop triggering", "Raise an exception"], 1,
    "Correcting levels on items whose movement class fell is the lowest-cost prevention in the module."),
  C("The upstream reads route their findings to:",
    ["The stock manager", "The function that acts on them",
     "The monthly review", "The owner"], 1,
    "Reorder hygiene to stock, aging profile by supplier to procurement, and so on."),
  C("Two standing figures route to the procurement owner monthly, including:",
    ["The turns figure", "The aging profile by supplier",
     "The count accuracy", "The transit balance"], 1,
    "Purchasing feedback is a read rather than a complaint.")],
 6: [
  C("Stock turns is cost of goods sold across the period divided by:",
    ["Closing stock value", "Average stock value across the period",
     "Opening stock value", "Purchases"], 1,
    "Annualised per the policy's convention, and computed per item group as well as for the whole."),
  C("Turns should be compared per item group against their own history and:",
    ["A single company target", "The policy's expectation per group",
     "The industry average", "The prior year only"], 1,
    "Fast-moving retail groups turn faster than equipment ranges by nature."),
  C("Turns improving means:",
    ["Sales have risen", "The same sales carried on less investment",
     "Stock value has fallen", "Margins improved"], 1,
    "Which is why the figure summarises the whole module's effect in one number.")],
 7: [
  C("HealthTrade's first aging compile found the over-ninety band holding:",
    ["₦620,000", "₦6.2m, or 9.6% of total stock value",
     "₦62m", "Under 2% of value"], 1,
    "Concentrated at Central, with the working list running to several pages."),
  C("The volume cell of the two-dimensional read held:",
    ["A short individual list", "140 C-class SKUs with negligible movement across two quarters",
     "The high-value items", "The expiring batches"], 1,
    "Handled as a group, while the priority cell's short list was worked individually."),
  C("The high-value dead cell was:",
    ["Batched for markdown", "Worked individually",
     "Deferred to the next quarter", "Written off"], 1,
    "Value ranking and movement class together decide which treatment an item gets.")],
 8: [
  C("Aging reports compiled and filed with no decisions attached is:",
    ["A reasonable first stage", "Reads without lanes",
     "Correct until volumes grow", "An analytical baseline"], 1,
    "Every list feeds a lane, and second-month undecided items escalate."),
  C("Aged stock discounted at the site it aged at while other sites sell it at full price is:",
    ["Efficient clearance", "Markdown as the first response",
     "Correct where transfer costs are high", "The rebalancing lane"], 1,
    "The divergence read runs first, and laterals go where the data supports them."),
  C("The prevention for reads without lanes is:",
    ["More frequent reporting", "The read-and-lane structure",
     "Escalating all aged stock", "Automatic markdown"], 1,
    "A read that produces no decision is a report rather than a control.")],
},
"advanced_inventory": {
 0: [
  C("The structural layer is its own module because the operating procedures of modules 1 to 7:",
    ["Are optional", "Each rest on decisions that need owning, recording and reviewing",
     "Change frequently", "Belong to different roles"], 1,
    "Settings, the register, the lifecycle, the roles, the records and the multi-company structure."),
  C("The register exists so that any past posture is:",
    ["Reversible", "Answerable",
     "Auditable annually", "Recoverable from backups"], 1,
    "Superseded rows are retained with their dates rather than overwritten."),
  C("The structural layer is what makes the operating procedures:",
    ["Faster", "Survive the people who set them up",
     "Cheaper to run", "Auditable"], 1,
    "Decisions with owners and review dates rather than configuration nobody can explain.")],
 1: [
  C("Every departure from a recommended posture in Stock Settings is:",
    ["Permitted if justified verbally", "A register entry with a reason",
     "Escalated to the owner", "Reviewed at year end"], 1,
    "The walk runs in order, and each field carries a recommended posture."),
  C("Anything landing in the global Default Warehouse should be treated by the monthly fallback read as:",
    ["Normal traffic", "A wiring gap",
     "A count exception", "A transit item"], 1,
    "It is the final fallback of the resolution chain, not a destination."),
  C("Changing Item Naming By mid-register is:",
    ["A settings preference", "A governed event",
     "Prevented by the system", "Done at year end"], 1,
    "Decided once at implementation and changed deliberately if at all.")],
 2: [
  C("Each row of the control register carries the control, its value, the owner, the reason, the date decided and:",
    ["The system field", "The next review date",
     "The approver", "The affected module"], 1,
    "One row per control, version-kept, so every posture has an owner and a date it is next examined."),
  C("The register is version-kept, meaning superseded rows are:",
    ["Deleted", "Retained with their dates",
     "Archived annually", "Replaced in place"], 1,
    "So that any past posture can be explained rather than reconstructed."),
  C("A control change is not complete until:",
    ["It is tested", "Its register row is updated",
     "The owner signs", "The review date passes"], 1,
    "Otherwise the register describes a past configuration.")],
 3: [
  C("A duplicate item splits one product's history across two records, producing stock in two places, reorder arithmetic on half the data and:",
    ["Slower reporting", "Counts that disagree by construction",
     "Valuation errors", "Identity gaps"], 1,
    "The gate's duplicate search takes one minute; the merge remediation later takes days."),
  C("The duplicate check searches by name fragments, barcode and:",
    ["Item group", "Supplier reference",
     "Warehouse", "Creation date"], 1,
    "Before the item is created rather than after."),
  C("Identity flags are applied at creation:",
    ["Per the creator's judgement", "From the class row in the control table",
     "By the receiving team", "At the first movement"], 1,
    "Which is why the register's class table exists.")],
 4: [
  C("Stock Manager rights — reconciliations, backdating, cancellations, settings — should be held by:",
    ["The site team", "Named individuals",
     "Whoever covers the shift", "The stock function generally"], 1,
    "Held by named individuals rather than by whoever happens to need the power that week."),
  C("The exception roles — frozen-stock editing, over-delivery tolerance, the recall freeze authority — are each:",
    ["Granted at implementation", "A register row with its named holders",
     "Held by the manager", "Time-limited"], 1,
    "So the holder of each unusual power is answerable rather than assumed."),
  C("The separation stated in the role design is that the keeper does not:",
    ["Count their own warehouse", "Approve their own adjustments",
     "Receive deliveries", "Hold the deputy role"], 1,
    "The person answerable for the stock is not the person who signs off its corrections.")],
 5: [
  C("Count files are filed:",
    ["By item", "Per warehouse per date",
     "Annually", "With the reconciliation only"], 1,
    "Signed sheets, the variance report, investigation notes and the posted reconciliation reference together."),
  C("Recall files are kept per event and:",
    ["Per batch", "Per drill",
     "Per site", "Per year"], 1,
    "The drill produces the same evidence as the real event, which is what makes it a test."),
  C("The filing map names:",
    ["A retention period only", "One location per file class",
     "The responsible role", "The archive schedule"], 1,
    "Named in the procedure, so evidence has a place before it is generated.")],
 6: [
  C("Where a site runs more than one legal entity, each company holds:",
    ["A shared warehouse tree", "Its own warehouse tree from its own root",
     "One tree with company groups", "Warehouses by site"], 1,
    "Stock structure follows the legal boundary."),
  C("Items across companies are:",
    ["Duplicated per company", "Shared on one register, with per-company defaults rows",
     "Kept separate entirely", "Linked by code"], 1,
    "With the decision recorded in the register."),
  C("The annual settings review on a multi-company site walks:",
    ["The primary company", "Each company",
     "Shared settings only", "The group configuration"], 1,
    "The register carries per-company rows where postures differ.")],
 7: [
  C("The first annual settings walk confirmed the negative-stock posture off, recording as its reason:",
    ["Policy", "The remediation project",
     "The auditor's finding", "The close calendar"], 1,
    "A posture with a reason attached is one the next person can understand."),
  C("Reorder automation was confirmed on only for:",
    ["Central", "The sites whose levels were set from data",
     "A items", "The branches"], 1,
    "Automation on levels that were guessed produces confident wrong orders."),
  C("The walk's output was:",
    ["A settings change list", "The register's first complete revision",
     "An audit report", "A training plan"], 1,
    "Every posture with an owner, a reason and a review date.")],
 8: [
  C("Postures set at implementation and never reviewed produce:",
    ["Stability", "Departures nobody can explain",
     "Consistent behaviour", "Fewer incidents"], 1,
    "The correction is running the settings walk and building the register."),
  C("A register describing a past configuration is corrected by:",
    ["Rebuilding it annually", "The quarterly confirmation against the live system",
     "Locking the settings", "Removing stale rows"], 1,
    "And prevented by the rule that a change is not complete until its row is updated."),
  C("Items created around the gate produce:",
    ["Slower reporting", "Duplicates splitting histories",
     "Missing defaults", "Identity gaps only"], 1,
    "Which is what the one-minute duplicate search at creation exists to prevent.")],
},
"warehouses": {
 0: [
  C("A shelf area, a cold room, a van and stock at a subcontractor can each be a warehouse if the business needs a separate answer to:",
    ["What it cost", "What is here, and who answers for it",
     "How fast it moves", "Which company owns it"], 1,
    "A Warehouse record is a named place stock can be, not necessarily a building."),
  C("One physical building may hold several warehouses because the record follows:",
    ["The floor plan", "Accountability",
     "The item categories", "The company structure"], 1,
    "Two areas sharing one keeper and one answer are one warehouse."),
  C("Stock held at a subcontractor is:",
    ["Off the books until returned", "A warehouse like any other",
     "A supplier balance", "An expense"], 1,
    "It remains the business's stock, so it needs a place and a keeper in the system.")],
 1: [
  C("A warehouse with Is Group ticked:",
    ["Holds stock and children", "Cannot hold stock",
     "Requires a keeper", "Is company-independent"], 1,
    "Group nodes exist for structure and reading; leaves hold the stock."),
  C("Warehouses on a multi-company site are:",
    ["Shared across entities", "Per company, each entity's stock in its own set",
     "Grouped centrally", "Linked by transit"], 1,
    "The legal separation rule applies to stock exactly as to everything else."),
  C("The Warehouse Name entered on the record is:",
    ["The full record ID", "The readable part, with the company abbreviation appended by the system",
     "An internal code", "Optional if a number is set"], 1,
    "It prints on every stock document and report, which is why the convention matters.")],
 2: [
  C("Two storage areas share one keeper and produce one answer. They should be:",
    ["Two warehouses", "One warehouse",
     "A group with two leaves", "One warehouse per item class"], 1,
    "The custody answer drives the structure, not the floor plan."),
  C("How many levels cover almost every business this track serves?",
    ["Two", "Three",
     "Five", "As many as the shelving"], 1,
    "Root, site groups, and the leaves that hold stock."),
  C("The warehouse tree should be designed:",
    ["As records are needed", "Once, on paper, before records are created",
     "After the first count", "By each site"], 1,
    "Retrofitting a tree means transferring stock by document into merged leaves.")],
 3: [
  C("How many transit warehouses does a company normally need?",
    ["One per branch", "One, or one per route where route-level visibility is wanted",
     "One per item class", "One per keeper"], 1,
    "Goods leaving a source site post into transit and the receiving site takes them out of it."),
  C("Warehouse Type records are read by reports and by:",
    ["The valuation engine", "The transfer machinery",
     "The costing method", "The count schedule"], 1,
    "Create the set once with the tree design."),
  C("Quarantine and Cold Chain as warehouse types are:",
    ["Built in", "Types the business adds",
     "Reserved for regulated goods", "Set per item"], 1,
    "The master carries the standard set plus whatever the business needs to classify.")],
 4: [
  C("A stock transaction row resolves its warehouse first from:",
    ["Stock Settings", "The warehouse typed on the row",
     "The Item Default", "The document header"], 1,
    "Row, then document header, then Item Default, then the global default."),
  C("A mis-wired default is dangerous because it:",
    ["Blocks the transaction", "Posts silently to the wrong place until a count finds it",
     "Requires an override", "Affects only new items"], 1,
    "A default is a convenience with consequences."),
  C("The Item Defaults table carries one row per:",
    ["Warehouse", "Company",
     "Item group", "Transaction type"], 1,
    "Which is what makes defaults workable on a multi-company site.")],
 5: [
  C("The figure on a Bin that the shelf should match is:",
    ["Projected Qty", "Actual Qty",
     "Reserved Qty", "Ordered Qty"], 1,
    "The sum of every posted stock movement for that item-warehouse pair."),
  C("Reserved Qty represents stock:",
    ["Held for quality checks", "Committed to submitted Sales Orders not yet delivered",
     "In transit", "Below reorder level"], 1,
    "It is a commitment rather than a physical state."),
  C("The Bin is maintained:",
    ["By the keeper", "By the system, from postings",
     "At each count", "By the reorder run"], 1,
    "One Bin per item per warehouse, standing balance.")],
 6: [
  C("A warehouse whose keeper is on leave with no deputy is:",
    ["Covered by the site group", "The unmarked-location failure in stock form",
     "Locked automatically", "Reassigned by the system"], 1,
    "The custody list carries a keeper and a deputy per leaf warehouse."),
  C("The custody list should be reviewed quarterly and:",
    ["At year end", "At every staffing change",
     "After each count", "When variances appear"], 1,
    "A leaver or mover on the custody list is a same-day update."),
  C("The keeper's responsibilities are to receive against documents, release against documents and:",
    ["Set the reorder levels", "Sign the counts",
     "Approve transfers", "Value the stock"], 1,
    "Which is what makes them the person who answers for the contents.")],
 7: [
  C("HealthTrade's paper tree kept to three levels and placed the transit and subcontract warehouses:",
    ["Under Central", "At root level",
     "Under each site group", "Outside the tree"], 1,
    "They serve the whole network rather than one site."),
  C("The custody walk of the physical sites was done:",
    ["After the records were created", "Before the tree was drawn",
     "At the first count", "By each branch separately"], 1,
    "The design inputs are the rooms needing separate accountability and who keeps each."),
  C("Central was given four leaves — main store, cold room, quarantine and dispatch — because each:",
    ["Is a separate building", "Needs its own answer and its own keeper",
     "Holds different item groups", "Has its own count cadence"], 1,
    "Function separation regardless of geography, plus the physical areas that need accountability.")],
 8: [
  C("'With Emeka' as a stock location is the symptom of:",
    ["A naming problem", "The person-shaped warehouse",
     "A missing default", "An untyped warehouse"], 1,
    "A place with a keeper can be a warehouse; an undocumented handover cannot."),
  C("Five-level trees mirroring shelves and aisles produce:",
    ["Precise reporting", "Every transaction as a navigation exercise",
     "Better counts", "Clearer custody"], 1,
    "The correction is flattening to the accountability units and transferring stock by document."),
  C("Nothing moves on:",
    ["A verbal instruction from the keeper", "A conversation",
     "An unapproved request", "A same-day entry"], 1,
    "The module rule: every movement has its document.")],
},
"stock_entries": {
 0: [
  C("Stock crosses the business boundary on other documents. The Stock Entry covers:",
    ["Purchases and sales", "Everything moving inside the boundary, plus the documented exceptions at it",
     "Adjustments only", "Transfers only"], 1,
    "In by Purchase Receipt, out by Delivery Note; everything else is a Stock Entry."),
  C("A Material Issue is described as a boundary exception because stock leaves:",
    ["Without approval", "Without a sale",
     "Without a document", "Without valuation"], 1,
    "And Material Receipt is its mirror — stock entering without a purchase."),
  C("The purposes reshape the form, which is why the purpose is selected:",
    ["Last, after the rows", "First",
     "By the approver", "From the item"], 1,
    "It determines which warehouses are required, whether accounts are asked for, and how value behaves.")],
 1: [
  C("Where the business has created named Stock Entry Types such as Damage Write-Off, you should select the specific one because it:",
    ["Changes the accounting", "Prints on the document and filters the reports",
     "Sets the approval route", "Determines the warehouse"], 1,
    "The type master maps named types onto the purposes."),
  C("Today's entry for yesterday's confirmed movement carries:",
    ["Today's date", "Yesterday's date",
     "The approval date", "The period-end date"], 1,
    "An entry never carries a date chosen to land in a different period."),
  C("Posting Date and Time state:",
    ["When the entry was made", "When the movement actually happened",
     "When it was approved", "When the period opens"], 1,
    "The gap between event and entry is where records and reality drift.")],
 2: [
  C("A pharmaceutical expiry write-off documents the stock side and references:",
    ["The supplier credit", "The disposal record",
     "The insurance claim", "The quarantine transfer"], 1,
    "Disposal regulations are held by the compliance owner; the issue is the stock document."),
  C("Both the issue and receipt lanes run on reason, account, evidence and:",
    ["Valuation", "Approval",
     "A count", "A transfer"], 1,
    "Each lawful case names its account and the evidence the written stock policy requires."),
  C("Goods the business uses itself are issued to:",
    ["The damage account", "The consumption expense account against the requesting unit's cost centre",
     "Suspense", "The subcontract warehouse"], 1,
    "Cleaning materials and own-use items are internal consumption rather than damage.")],
 3: [
  C("One-step transfers should be used only where:",
    ["The distance is short", "Both keepers can verify the same physical event",
     "The value is low", "No transit warehouse exists"], 1,
    "Which is what 'same site' means operationally."),
  C("Between sites the two-step transfer exists because the movement:",
    ["Crosses companies", "Takes time",
     "Needs approval", "Changes valuation"], 1,
    "Goods sit in transit under a documented custody rather than nowhere."),
  C("A transfer received 'complete' regardless of the count causes shortfalls to:",
    ["Be caught at the source", "Migrate into receiving warehouses as later unexplained variances",
     "Appear in transit", "Reverse automatically"], 1,
    "The receipt has to state what actually arrived.")],
 4: [
  C("In a Repack entry, the produced stock's total value equals:",
    ["The market value of the outputs", "The consumed stock's value plus any additional costs entered",
     "The consumed stock's value only", "The standard cost of the outputs"], 1,
    "The system distributes that value across the produced rows."),
  C("Repack is one entry containing:",
    ["Only produced rows", "Consumed rows and produced rows",
     "A transfer and a receipt", "Two linked documents"], 1,
    "Cartons into strips, bulk into bottles, or a bundle assembled from components."),
  C("Consumed rows in a Repack are valued:",
    ["At the produced rate", "By the ledger at their valuation rate, like any outgoing movement",
     "At standard cost", "At the last purchase price"], 1,
    "Value is conserved across the entry rather than created.")],
 5: [
  C("Materials sent to a subcontractor:",
    ["Leave the books", "Remain the business's stock",
     "Become a supplier balance", "Are expensed on despatch"], 1,
    "Which is why they move to a subcontract warehouse rather than out of inventory."),
  C("The commercial side of subcontracting — the order, terms and receipt of finished goods — belongs to:",
    ["This module", "The Procurement track",
     "The Selling track", "The Accounts track"], 1,
    "This module owns the stock side: materials leaving, sitting in vendor custody, and being consumed."),
  C("The subcontract warehouse may be per vendor or shared, according to:",
    ["The volume", "The recorded design",
     "The item class", "The vendor's preference"], 1,
    "Either is workable provided the choice is written down rather than accidental.")],
 6: [
  C("Backdating a Stock Entry requires a permitted role, the honest date and:",
    ["A second approval", "The reason in remarks",
     "A linked document", "A count"], 1,
    "It is the controlled exception rather than an ordinary practice."),
  C("A movement that surfaces after a period has closed:",
    ["Is backdated anyway", "Posts on the first open date",
     "Is left unrecorded", "Requires the period reopened"], 1,
    "Backdating into a closed period is refused by the close controls."),
  C("The standard for entering a movement is:",
    ["Within the week", "Same-day",
     "At the next count", "Before period end"], 1,
    "The despatch entered when the truck loads, the issue when the damage is confirmed.")],
 7: [
  C("At HealthTrade, damaged cartons found at Central were moved to quarantine:",
    ["At the month-end count", "The same morning",
     "After the supplier replied", "On the disposal date"], 1,
    "The goods are separated from sellable stock by a document rather than by intention."),
  C("The named Stock Entry Types printed on the documents and fed:",
    ["The valuation report", "The type census",
     "The reorder run", "The count schedule"], 1,
    "Which is what makes the movement traffic readable by category."),
  C("The routine weekly movements ran with:",
    ["Row-level warehouse overrides", "Header warehouses per the pair and no row overrides",
     "Manual date entry", "Approval on each entry"], 1,
    "Ordinary traffic should need no exceptions, which is what makes the exceptions visible.")],
 8: [
  C("Counts wrong at both ends in opposite directions indicates:",
    ["A valuation error", "An undocumented handover",
     "A transit problem", "A default misconfiguration"], 1,
    "The variance investigation then reconstructs what a document would simply have stated."),
  C("The prevention for the undocumented handover is:",
    ["More frequent counts", "The custody rule operated, with the same-day standard",
     "Tighter permissions", "A larger transit warehouse"], 1,
    "The custody rule plus the same-day standard: nothing moves without its document, and the document is entered the day it happens."),
  C("Shortfalls that migrate into receiving warehouses are corrected by:",
    ["Adjusting the receiving count", "Tracing the affected receipts and moving the losses to their honest documents",
     "A stock reconciliation", "Writing them off centrally"], 1,
    "The loss belongs where it happened rather than where it was discovered.")],
},
"serial_batch": {
 0: [
  C("Batch identity covers many units sharing a number, expiry and fate. Serial identity covers:",
    ["A delivery", "Each individual piece",
     "A warehouse", "A supplier lot"], 1,
    "The lot against the unit, and the choice follows what the business needs to trace."),
  C("Pharmaceuticals, foods and chemicals run under batch control because the manufacturer's lot is:",
    ["The purchase unit", "The unit of quality and recall",
     "The pricing unit", "The storage unit"], 1,
    "Anything a recall letter can name needs the lot carried in the system."),
  C("The identity structure exists so that the business can locate a batch across the network:",
    ["At the next count", "In minutes",
     "Within a day", "By branch enquiry"], 1,
    "Which is the whole purpose of the recall and freeze procedure.")],
 1: [
  C("The pharmaceutical standard for receiving batches is:",
    ["Automatically Create New Batch on", "Auto-create off, with the manufacturer's number captured from the carton",
     "A branch-specific series", "Batch numbers assigned at sale"], 1,
    "A recall letter names the manufacturer's number, and a system substitute makes the freeze a translation exercise."),
  C("Identity flags should be set from:",
    ["Per-item judgement at creation", "The written control register",
     "The supplier's practice", "The item group default"], 1,
    "The register decides the posture per class, so identical items are not configured differently by whoever created them."),
  C("Ticking Has Batch No means every stock movement of the item will:",
    ["Require approval", "Require a batch number",
     "Post to quarantine", "Need a serial"], 1,
    "Every movement of the item carries a batch number, and balances are held per batch rather than per item.")],
 2: [
  C("The Expiry Date on a Batch record should be entered:",
    ["From the packing list", "From the printed label, at the dock, by the receiver",
     "From the purchase order", "By the compliance owner"], 1,
    "Checked by the second signature on the receiving document, because the whole expiry read structure hangs on it."),
  C("A Batch record belongs to:",
    ["A supplier", "One item",
     "A warehouse", "A delivery"], 1,
    "One Batch record per lot per item, so the same manufacturer number on two different items is two records."),
  C("The Batch ID under the manual posture is:",
    ["A system series value", "The manufacturer's batch number",
     "The receipt number", "A site code plus date"], 1,
    "It is the record's name and prints everywhere.")],
 3: [
  C("A Serial No record shows where the unit stands, maintained by:",
    ["The keeper", "The documents that move it",
     "The count", "A monthly job"], 1,
    "In which warehouse, delivered, or otherwise disposed."),
  C("Warranty expiry on a Serial No is computed from:",
    ["The manufacture date", "The item's warranty period and the delivery date",
     "The receipt date", "The batch expiry"], 1,
    "Which is why delivery documents matter to the service flows."),
  C("Serial No records are normally created:",
    ["At sale", "At receipt",
     "At the count", "When a warranty claim arises"], 1,
    "And read thereafter as the unit's document trail.")],
 4: [
  C("Three lots arriving on one line should be entered as:",
    ["One batch chosen for convenience", "Three bundle entries",
     "A mixed batch record", "One batch with a note"], 1,
    "Mixed-lot deliveries are split honestly at the dock."),
  C("Serial capture at the dock requires that the physical unit count:",
    ["Be estimated", "Equal the quantity, with discrepancies stopped at the dock",
     "Be checked at the next count", "Match the purchase order"], 1,
    "A discrepancy accepted at receipt becomes an unexplained variance later."),
  C("The Purchase Receipt of a controlled item is described as:",
    ["A routine posting", "The module's most important fifteen minutes",
     "The compliance owner's task", "A two-person job only for serials"], 1,
    "Identity is born there, and everything downstream depends on what was captured.")],
 5: [
  C("The target for the weekly expired list is:",
    ["Under five lines", "Zero",
     "Falling month on month", "Below a value"], 1,
    "Every line is a lane that did not run in time, and the line's age is the process gap's size."),
  C("The expiry reads are exactly as good as:",
    ["The count cadence", "The Expiry Date field on Batch records",
     "The warehouse structure", "The reorder levels"], 1,
    "Which is what the monthly identity audit riding the counts exists to protect."),
  C("Expired stock appearing on the weekly list means it:",
    ["Was correctly quarantined", "Should have left the trading warehouses before its date",
     "Is awaiting disposal approval", "Was received late"], 1,
    "The lanes exist to move it out ahead of expiry rather than after.")],
 6: [
  C("Setting a Batch record to Disabled blocks new transactions on it:",
    ["At the site that set it", "Network-wide, at every site simultaneously",
     "After a sync", "For sales only"], 1,
    "No till can sell it and no transfer can move it, from that moment."),
  C("The target for the freeze step is:",
    ["The same day", "Fifteen minutes from notice",
     "Within an hour", "Before the next despatch"], 1,
    "Each step in the procedure has a time target, sequenced for speed."),
  C("The freeze switch is why manual manufacturer batch numbers matter, because the recall letter:",
    ["Arrives by post", "Names the manufacturer's number",
     "Specifies a date range", "Is issued per site"], 1,
    "A system-generated number would make the first step a research project.")],
 7: [
  C("The Ibadan till's attempt to sell a strip of B-1147 at 09:10 was:",
    ["Allowed with a warning", "Refused by the system before the branch had finished reading the notification",
     "Recorded for reversal", "Blocked by the keeper"], 1,
    "The freeze had been set at 08:55, and it applies at every site at once."),
  C("The batch was found in one search because:",
    ["The recall named a date", "Receiving discipline had stored the manufacturer's own number",
     "The item was serialised", "It sat in one warehouse"], 1,
    "Notice-to-freeze was fifteen minutes as a direct consequence."),
  C("The keeper message at 08:52 named the item, the batch and:",
    ["The disposal route", "The segregation instruction",
     "The supplier", "The expiry date"], 1,
    "Freeze first, then tell the people who physically hold it what to do.")],
 8: [
  C("A recall letter naming a number the system has never heard of is caused by:",
    ["A supplier error", "Auto-created batch numbers on regulated goods",
     "A missing expiry date", "An item misconfiguration"], 1,
    "The freeze step becomes a research project at exactly the wrong moment."),
  C("Expiry dates entered from paperwork rather than labels mis-schedule the reads for:",
    ["That month", "The life of every mis-entered lot",
     "One quarter", "Until the next count"], 1,
    "The identity audit re-checking labels against Batch records is the correction."),
  C("The prevention for system batches over manufacturer lots is:",
    ["Tighter receiving approval", "The control register setting the posture per class",
     "More frequent audits", "Serial control instead"], 1,
    "Manual manufacturer numbers wherever a recall can name them.")],
},
}


def rebalance(items, seed):
    n = len(items)
    base, extra = divmod(n, 4)
    slots = []
    for i in range(4):
        slots += [i] * (base + (1 if i < extra else 0))
    random.Random(seed).shuffle(slots)
    for it, target in zip(items, slots):
        cur = it["ans"]
        if cur == target:
            continue
        shift = (target - cur) % 4
        it["opts"] = it["opts"][-shift:] + it["opts"][:-shift]
        it["ans"] = target
    return items


def main():
    data = json.load(io.open(DATA, encoding="utf-8"))

    for mod_key, chapters in CHECKS.items():
        if mod_key not in data:
            sys.exit("ABORT: module %r not in %s" % (mod_key, DATA))
        flat = [c for _i, ch in sorted(chapters.items()) for c in ch]
        rebalance(flat, "inventory:%s:checks" % mod_key)

    added = skipped = 0
    problems = []
    for mod_key, chapters in CHECKS.items():
        lessons = data[mod_key]["lessons"]
        # every chapter of a module being touched must be covered
        missing = [i + 1 for i in range(len(lessons)) if i not in chapters]
        if missing:
            problems.append("%s: no checks written for chapter(s) %s" % (mod_key, missing))
        bank = {re.sub(r"[^a-z0-9 ]", "", q["q"].lower()).strip()
                for q in data[mod_key].get("questions") or []}
        seen = set()
        for idx, checks in sorted(chapters.items()):
            if idx >= len(lessons):
                sys.exit("ABORT: %s has no chapter %d" % (mod_key, idx + 1))
            if len(checks) != 3:
                problems.append("%s ch%d has %d checks" % (mod_key, idx + 1, len(checks)))
            for c in checks:
                norm = re.sub(r"[^a-z0-9 ]", "", c["q"].lower()).strip()
                if norm in bank:
                    problems.append("duplicates exam question: %s" % c["q"][:58])
                if norm in seen:
                    problems.append("duplicate check: %s" % c["q"][:58])
                seen.add(norm)
                if len(c.get("why") or "") < 40:
                    problems.append("weak rationale: %s" % c["q"][:50])
                if len(c["opts"]) != 4:
                    problems.append("not 4 options: %s" % c["q"][:50])
            l = lessons[idx]
            if l.get("checks") and not FORCE:
                skipped += 1
                continue
            if not CHECK_ONLY:
                l["checks"] = [dict(c, sort=i) for i, c in enumerate(checks)]
            added += len(checks)

    if problems:
        print("ABORT — %d problem(s):" % len(problems))
        for p in problems:
            print("   %s" % p)
        sys.exit(1)

    print("checks to add: %d | chapters already done: %d" % (added, skipped))
    if CHECK_ONLY:
        print("--check given; nothing written.")
        return

    with io.open(DATA, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write("\n")

    chs = sum(len(m["lessons"]) for m in data.values())
    done = sum(1 for m in data.values() for l in m["lessons"] if l.get("checks"))
    tot = sum(len(l.get("checks") or []) for m in data.values() for l in m["lessons"])
    print("track now: %d of %d chapters have checks, %d checks total" % (done, chs, tot))
    sp = collections.Counter(c["ans"] for m in data.values()
                             for l in m["lessons"] for c in (l.get("checks") or []))
    print("answer spread:", dict(sorted(sp.items())))


if __name__ == "__main__":
    main()
